-- ============================================================
-- packs/standard/050_apqp_catalog.sql — APQP 카탈로그 — 단계 5·산출물 43(team NULL·status 리셋) ※ PPAP/FMEA/MSA 데모 인스턴스는 제외
-- 자동 생성: scripts/gen-pack-standard.mjs (손편집 금지 — 재작성·제외 목록도 생성기에 있음)
-- 근거: 40호 ④ 도장(2026-08-19) · 39호 S3 · 실명 0·회사식별 0(생성기 게이트)
-- ============================================================
INSERT OR IGNORE INTO apqp_phases (id, phase_no, title, title_en, description, sort_order) VALUES
  ('phase-1', 1, '계획 및 정의', 'Plan and Define Program', '고객의 소리를 바탕으로 제품 프로그램을 계획하고 설계·품질 목표를 정의한다.', 1),
  ('phase-2', 2, '제품 설계 및 개발', 'Product Design and Development', '설계 특성과 기술 요구사항을 구체화하고 설계 타당성을 검증한다.', 2),
  ('phase-3', 3, '공정 설계 및 개발', 'Process Design and Development', '양산 공정 시스템과 관리 방법을 개발하고 양산전 관리계획서를 수립한다.', 3),
  ('phase-4', 4, '제품 및 공정 검증', 'Product and Process Validation', '양산 시험가동을 통해 제품과 공정을 검증하고 양산부품승인(PPAP)을 완료한다.', 4),
  ('phase-5', 5, '피드백, 평가 및 시정조치', 'Feedback, Assessment and Corrective Action', '변동을 감소시키고 고객만족·교훈을 반영하여 지속적으로 개선한다.', 5);
INSERT OR IGNORE INTO apqp_elements (id, phase_id, seq, name, name_en, io, core_tool, clause_id, team_id, status, sort_order) VALUES
  ('apqp-1-01', 'phase-1', 1, '고객의 소리(VOC) 수집', 'Voice of the Customer', 'input', NULL, NULL, NULL, 'not_started', 1),
  ('apqp-1-02', 'phase-1', 2, '설계 목표', 'Design Goals', 'output', NULL, NULL, NULL, 'not_started', 2),
  ('apqp-1-03', 'phase-1', 3, '신뢰성 및 품질 목표', 'Reliability and Quality Goals', 'output', NULL, NULL, NULL, 'not_started', 3),
  ('apqp-1-04', 'phase-1', 4, '예비 자재 명세서(BOM)', 'Preliminary Bill of Material', 'output', NULL, NULL, NULL, 'not_started', 4),
  ('apqp-1-05', 'phase-1', 5, '예비 공정 흐름도', 'Preliminary Process Flow Chart', 'output', NULL, NULL, NULL, 'not_started', 5),
  ('apqp-1-06', 'phase-1', 6, '예비 특별특성 목록', 'Preliminary Listing of Special Characteristics', 'output', NULL, NULL, NULL, 'not_started', 6),
  ('apqp-1-07', 'phase-1', 7, '제품보증계획', 'Product Assurance Plan', 'output', NULL, NULL, NULL, 'not_started', 7),
  ('apqp-1-08', 'phase-1', 8, '경영자 지원', 'Management Support', 'output', NULL, NULL, NULL, 'not_started', 8),
  ('apqp-2-01', 'phase-2', 1, '설계 FMEA (DFMEA)', 'Design FMEA', 'output', 'FMEA', NULL, NULL, 'not_started', 9),
  ('apqp-2-02', 'phase-2', 2, '설계 검증(DV)', 'Design Verification', 'output', NULL, NULL, NULL, 'not_started', 10),
  ('apqp-2-03', 'phase-2', 3, '설계 검토', 'Design Reviews', 'output', NULL, NULL, NULL, 'not_started', 11),
  ('apqp-2-04', 'phase-2', 4, '시작품 관리계획서', 'Prototype Build Control Plan', 'output', 'CP', NULL, NULL, 'not_started', 12),
  ('apqp-2-05', 'phase-2', 5, '엔지니어링 도면', 'Engineering Drawings', 'output', NULL, NULL, NULL, 'not_started', 13),
  ('apqp-2-06', 'phase-2', 6, '엔지니어링 사양', 'Engineering Specifications', 'output', NULL, NULL, NULL, 'not_started', 14),
  ('apqp-2-07', 'phase-2', 7, '자재 사양', 'Material Specifications', 'output', NULL, NULL, NULL, 'not_started', 15),
  ('apqp-2-08', 'phase-2', 8, '신규 장비·금형·설비 요구사항', 'New Equipment, Tooling and Facilities Requirements', 'output', NULL, NULL, NULL, 'not_started', 16),
  ('apqp-2-09', 'phase-2', 9, '제품·공정 특별특성', 'Special Product and Process Characteristics', 'output', NULL, NULL, NULL, 'not_started', 17),
  ('apqp-2-10', 'phase-2', 10, '게이지·시험장비 요구사항', 'Gages / Testing Equipment Requirements', 'output', NULL, NULL, NULL, 'not_started', 18),
  ('apqp-2-11', 'phase-2', 11, '팀 타당성 확약', 'Team Feasibility Commitment', 'output', NULL, NULL, NULL, 'not_started', 19),
  ('apqp-3-01', 'phase-3', 1, '포장 표준', 'Packaging Standards', 'output', NULL, NULL, NULL, 'not_started', 20),
  ('apqp-3-02', 'phase-3', 2, '제품·공정 품질시스템 검토', 'Product / Process Quality System Review', 'output', NULL, NULL, NULL, 'not_started', 21),
  ('apqp-3-03', 'phase-3', 3, '공정 흐름도', 'Process Flow Chart', 'output', NULL, NULL, NULL, 'not_started', 22),
  ('apqp-3-04', 'phase-3', 4, '공장 배치도(Floor Plan)', 'Floor Plan Layout', 'output', NULL, NULL, NULL, 'not_started', 23),
  ('apqp-3-05', 'phase-3', 5, '특성 매트릭스', 'Characteristics Matrix', 'output', NULL, NULL, NULL, 'not_started', 24),
  ('apqp-3-06', 'phase-3', 6, '공정 FMEA (PFMEA)', 'Process FMEA', 'output', 'FMEA', NULL, NULL, 'not_started', 25),
  ('apqp-3-07', 'phase-3', 7, '양산전 관리계획서(Pre-Launch CP)', 'Pre-Launch Control Plan', 'output', 'CP', NULL, NULL, 'not_started', 26),
  ('apqp-3-08', 'phase-3', 8, '작업표준서·공정지침서', 'Process Instructions', 'output', NULL, NULL, NULL, 'not_started', 27),
  ('apqp-3-09', 'phase-3', 9, '측정시스템분석(MSA) 계획', 'Measurement Systems Analysis Plan', 'output', 'MSA', NULL, NULL, 'not_started', 28),
  ('apqp-3-10', 'phase-3', 10, '초기 공정능력 연구 계획', 'Preliminary Process Capability Study Plan', 'output', 'SPC', NULL, NULL, 'not_started', 29),
  ('apqp-3-11', 'phase-3', 11, '경영자 지원', 'Management Support', 'output', NULL, NULL, NULL, 'not_started', 30),
  ('apqp-4-01', 'phase-4', 1, '양산 시험가동(Production Trial Run)', 'Production Trial Run', 'output', NULL, NULL, NULL, 'not_started', 31),
  ('apqp-4-02', 'phase-4', 2, '측정시스템분석(MSA)', 'Measurement Systems Analysis', 'output', 'MSA', NULL, NULL, 'not_started', 32),
  ('apqp-4-03', 'phase-4', 3, '초기 공정능력 연구', 'Preliminary Process Capability Study', 'output', 'SPC', NULL, NULL, 'not_started', 33),
  ('apqp-4-04', 'phase-4', 4, '양산부품승인(PPAP)', 'Production Part Approval Process', 'output', 'PPAP', NULL, NULL, 'not_started', 34),
  ('apqp-4-05', 'phase-4', 5, '양산 검증 시험', 'Production Validation Testing', 'output', NULL, NULL, NULL, 'not_started', 35),
  ('apqp-4-06', 'phase-4', 6, '포장 평가', 'Packaging Evaluation', 'output', NULL, NULL, NULL, 'not_started', 36),
  ('apqp-4-07', 'phase-4', 7, '양산 관리계획서(Production CP)', 'Production Control Plan', 'output', 'CP', NULL, NULL, 'not_started', 37),
  ('apqp-4-08', 'phase-4', 8, '품질계획 승인(Sign-Off)', 'Quality Planning Sign-Off', 'output', NULL, NULL, NULL, 'not_started', 38),
  ('apqp-4-09', 'phase-4', 9, '경영자 지원', 'Management Support', 'output', NULL, NULL, NULL, 'not_started', 39),
  ('apqp-5-01', 'phase-5', 1, '변동 감소', 'Reduced Variation', 'output', 'SPC', NULL, NULL, 'not_started', 40),
  ('apqp-5-02', 'phase-5', 2, '고객 만족', 'Customer Satisfaction', 'output', NULL, NULL, NULL, 'not_started', 41),
  ('apqp-5-03', 'phase-5', 3, '인도 및 서비스', 'Delivery and Service', 'output', NULL, NULL, NULL, 'not_started', 42),
  ('apqp-5-04', 'phase-5', 4, '교훈(Lessons Learned)·모범사례', 'Lessons Learned / Best Practices', 'output', NULL, NULL, NULL, 'not_started', 43);
