-- ============================================================
-- packs/standard/080_forms_catalog.sql — 양식 카탈로그 — 294종(표준 xlsx 템플릿 238종 = templates/standard/)(체인 302 − 제외 8: 사업부 전용·타사업부 열람형 / 사업부 scope 3종은 SQ 미니멀 정션 참조라 공통 편입) · ④-1 코드 체계 채택 · 이름 접미 정리 · 설명 = 봇 집필 258 + 규정 자동 36 (NULL 0) · scope '공통' 통일
-- 자동 생성: scripts/gen-pack-standard.mjs (손편집 금지 — 재작성·제외 목록도 생성기에 있음)
-- 근거: 40호 ④ 도장(2026-08-19) · 39호 S3 · 실명 0·회사식별 0(생성기 게이트)
-- ============================================================
INSERT OR IGNORE INTO forms (code, name, reg_code, description, approvals_json, next_form_code, next_form_label, prev_form_code, layout_json, scope, deprecated, deprecated_note, replacement_page, resp_dept, iatf_clause, sq_item_ids, template_path)
SELECT column1, column2, column3, column4, column5, column6, column7, column8, column9, column10, column11, column12, column13, column14, column15, column16, column17 FROM (VALUES
  ('A-2100', '사업계획 운영 규정', 'A-2100', '「사업계획 운영 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6', NULL, NULL),
  ('A-3100', '회의운영 규정', 'A-3100', '「회의운영 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, NULL),
  ('A-4101', '관리표준 작성 지침', 'A-4101', '「관리표준 작성 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('A-6300', '품질문제 신고포상 규정', 'A-6300', '「품질문제 신고포상 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', NULL, NULL, NULL),
  ('A-8101', '비상상태 대비 및 대응 규정', 'A-8101', '「비상상태 대비 및 대응 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, NULL),
  ('A1100-01', '개인별 업무 분장표', 'A-1100', '부서별로 사람마다 맡은 업무를 적는 분장표. 조직 변경·입퇴사 때 갱신하며, 심사에서는 ''이 업무의 책임자가 누구인가''의 근거로 쓰입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, 'templates/standard/A1100-01.xlsx'),
  ('A1100-02', '업무분장 변경 신청서', 'A-1100', '업무 분장이 바뀔 때(담당 교체·겸직) 제출하는 신청서. 승인 뒤 개인별 업무 분장표를 갱신합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, 'templates/standard/A1100-02.xlsx'),
  ('A2200-01', '회의록', 'A-2200', '경영검토·품질회의 등 공식 회의의 기록. 참석자·안건·결정사항·조치 담당/기한이 있어야 ''회의가 실행으로 이어졌다''는 증거가 됩니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, 'templates/standard/A2200-01.xlsx'),
  ('A2200-02', '경영검토 계획서', 'A-2200', '연 1회 이상 하는 경영검토의 일정·검토 항목·참석 범위를 정하는 계획서. 검토 입력 항목(IATF 9.3.2)이 빠짐없이 들어가야 합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, 'templates/standard/A2200-02.xlsx'),
  ('A2200-03', '경영검토 보고서', 'A-2200', '경영검토 결과 보고서. 항목별 현황·문제점·경영진 결정(자원·개선)과 후속 조치를 적습니다. 심사 필수 문서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, 'templates/standard/A2200-03.xlsx'),
  ('A3200-01', '이해관계자 불만 조치대장', 'A-3200', '고객·협력사·지역사회 등 이해관계자 불만의 접수~조치~종결을 번호로 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A3200-01.xlsx'),
  ('A3200-02', '이해관계자 불만 조치일지', 'A-3200', '이해관계자 불만 1건의 접수 내용·원인·조치·회신을 적는 개별 일지. 대장과 번호로 연결합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A3200-02.xlsx'),
  ('A4100-01', '회사표준관리대장', 'A-4100', '사내 표준(규정·지침)의 제정·개정·폐지 이력을 관리하는 대장. 현행본 Rev와 배포 상태를 한눈에 보여 줍니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-01.xlsx'),
  ('A4100-02', '표준 제개정 신청서', 'A-4100', '규정·지침을 새로 만들거나 고칠 때 내는 신청서. 개정 사유와 영향 범위를 적고 승인 뒤 표준관리대장에 반영합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-02.xlsx'),
  ('A4100-03', '기술표준관리대장', 'A-4100', '기술표준(검사기준·작업조건 등)의 제·개정 이력 대장. 현장 게시본과 원본 Rev가 같은지가 심사 포인트입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-03.xlsx'),
  ('A4100-04', '자료관리대장', 'A-4100', '외부 출처 자료(고객 규격·법규·KS 등)의 입수·배포·폐기 관리대장. 최신판 여부 확인 주기를 같이 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-04.xlsx'),
  ('A4100-05', '양식 제개정 신청서', 'A-4100', '양식을 새로 만들거나 고칠 때 내는 신청서. 승인 뒤 양식등록대장에 등록하고 구 양식은 회수합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-05.xlsx'),
  ('A4100-06', '양식등록대장', 'A-4100', '사내 전 양식의 코드·명칭·Rev·담당 부서를 등록한 대장. 현장에서 쓰는 양식이 여기 등록된 Rev인지 대조합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-06.xlsx'),
  ('A4200-01', '보존기록목록표', 'A-4200', '보존해야 할 기록의 종류·보존기간·보관 장소·담당을 정한 목록. 기록관리 규정의 실행표입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A4200-01.xlsx'),
  ('A4200-02', '기록분류표', 'A-4200', '기록을 분류(품질·환경·안전 등)하고 보존 등급을 정한 표. 보존기록목록표의 상위 기준입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A4200-02.xlsx'),
  ('A4200-03', '폐기기록 목록표', 'A-4200', '보존기간이 끝나 폐기한 기록의 목록. 폐기일·방법·승인자를 남겨 ''임의 폐기''가 아님을 증명합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A4200-03.xlsx'),
  ('A5100-01', '내부심사 년간 계획 및 실적', 'A-5100', '3개년 내부심사 연간 계획과 실적을 한 표에 적는 양식. 분기별 공정심사·프로세스별 시스템심사의 계획(○)과 실시(●)를 표시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-01.xlsx'),
  ('A5100-02', '내부심사 실시 계획서', 'A-5100', '내부심사 1회분의 실시 계획서. 심사 구분·대상 부서·심사팀·일정과 점수표를 담습니다. 심사원 독립성(자기 부서 심사 금지)이 포인트.', '["팀장","사업부장","사장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-02.xlsx'),
  ('A5100-03', '내부심사(갑지) 보고서', 'A-5100', '내부심사 결과 보고서(갑지). 긍정적 측면·부적합 내역·공정/제품 심사 결과를 적고 시정조치 요구서와 번호로 연결합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-03.xlsx'),
  ('A5100-04', '내부심사(품질,환경,안전) 체크리스트', 'A-5100', '품질·환경·안전 시스템 내부심사 체크리스트. 문항별 적합/부적합과 근거를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-04.xlsx'),
  ('A5200-03', '내부심사(제조) 체크리스트', 'A-5200', '제조 공정 내부심사 체크리스트. 공정별 문항과 지적사항을 적고 제품 심사와 짝을 이룹니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5200-03.xlsx'),
  ('A5200-04', '내부심사(제품) 체크리스트', 'A-5200', '제품 심사 체크리스트. 생산된 제품을 뽑아 치수·외관·기능을 기준과 대조한 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5200-04.xlsx'),
  ('A5200-04-01', '내부심사 성적서', 'A-5200', '내부심사 성적서. 조·구역별 생산품 평가 결과를 서술해 공정·제품 심사의 증거로 남깁니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5200-04-01.xlsx'),
  ('A6100-01', '나의 제안', 'A-6100', '직원 개인이 내는 개선 제안서. 문제점·개선안·기대효과를 적고 심사 결과(채택/포상)를 받습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6100-01.xlsx'),
  ('A6100-02', '제안관리대장', 'A-6100', '접수된 제안의 번호·제안자·내용·심사 결과·포상을 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6100-02.xlsx'),
  ('A6100-03', '제안종합현황', 'A-6100', '부서별 제안 건수·채택률 등 제안 활동 종합 현황표. 경영검토 입력 자료로 씁니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6100-03.xlsx'),
  ('A6200-01', '분임조 등록카드', 'A-6200', '분임조(소집단 개선 활동) 등록 카드. 조 이름·구성원·활동 테마를 등록합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-01.xlsx'),
  ('A6200-02', '분임조 활동계획서', 'A-6200', '분임조의 활동 테마·목표·일정 계획서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-02.xlsx'),
  ('A6200-03', '분임조 활동 회의록', 'A-6200', '분임조 회합 기록. 일시·참석자·논의 내용·다음 과제를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-03.xlsx'),
  ('A6200-04', '분임조 결과보고서', 'A-6200', '분임조 활동 결과 보고서. 개선 전/후 효과를 수치로 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-04.xlsx'),
  ('A6300-01', '품질문제 신고서', 'A-6300', '품질 문제를 발견한 직원이 내는 신고서. 신고 내용·발견 경위를 적고 포상 심사로 이어집니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', NULL, NULL, 'templates/standard/A6300-01.xlsx'),
  ('A7100-01', '윤리경영행동지침', 'A-7100', '열람형 — 윤리경영 행동 지침(서약서). 지침 본문과 서약란으로 된 참조 문서이며 체결은 서면 서명으로 합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, NULL),
  ('A7100-02', '클린신고서', 'A-7100', '윤리 위반·부정 행위를 신고하는 클린 신고서. 신고자 보호 원칙에 따라 접수됩니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, 'templates/standard/A7100-02.xlsx'),
  ('A8100-01', 'RISK 분석표', 'A-8100', '프로세스별 리스크를 찾아 발생 가능성·심각도로 평가하고 대응책을 적는 분석표(IATF 6.1). 연 1회 이상 갱신합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '6', NULL, 'templates/standard/A8100-01.xlsx'),
  ('A8101-01', '비상사태 발생시 대응 방안', 'A-8101', '열람형 — 비상사태(화재·정전·재해) 발생 시 대응 절차·연락 체계·상황별 방안을 담은 책자형 참조 문서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, NULL),
  ('A8101-02', '비상사태 대비 훈련결과 보고서', 'A-8101', '비상 대응 훈련을 실시한 뒤 쓰는 결과 보고서. 훈련 시나리오·참석 인원·소요 시간·문제점을 적습니다. 연 1회 이상 훈련 증거.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, 'templates/standard/A8101-02.xlsx'),
  ('A8101-03', '비상사태 대비 훈련 평가표', 'A-8101', '비상 대응 훈련의 평가표. 항목별 점수와 개선 필요 사항을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, 'templates/standard/A8101-03.xlsx'),
  ('A8101-04', '비상사태 검토 보고서', 'A-8101', '비상 대응 계획을 주기적으로 검토한 회의 기록. 연락망·장비·절차의 최신성을 확인합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, 'templates/standard/A8101-04.xlsx'),
  ('B-2200', '지속적 개선업무 규정', 'B-2200', '「지속적 개선업무 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, NULL),
  ('B1100-01', '부적합품 발생 통보서', 'B-1100', '공정/수입검사에서 부적합품 발생 시 작성. IATF §10.2 부적합 및 시정조치.', '["담당","팀장","사업부장"]', 'B2100-01', '이 부적합에 대한 시정조치를 요구합니다', NULL, '{
  "blocks": [
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "h1", "colSpan": 3 } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "h2" }, { "fieldKey": "h3" }, { "fieldKey": "h4" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "i1" }, { "fieldKey": "i2" }, { "fieldKey": "i3" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "i4" }, { "fieldKey": "i5" }, { "fieldKey": "i6" } ] },
    { "type": "section", "title": "부적합 내용" },
    { "type": "full", "fieldKey": "c1" },
    { "type": "full", "fieldKey": "c2" },
    { "type": "section", "title": "조사 내용" },
    { "type": "full", "fieldKey": "c3" },
    { "type": "section", "title": "조치 및 요구사항" },
    { "type": "grid", "columns": 1, "cells": [ { "fieldKey": "p1" }, { "fieldKey": "c4" }, { "fieldKey": "p3" } ] }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-01.xlsx'),
  ('B1100-02', '부적합품 발생 통보서 관리대장', 'B-1100', '부적합품 발생 통보서의 발행 번호·일자·품번·처리 결과를 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-02.xlsx'),
  ('B1100-03', '특채 의뢰서', 'B-1100', '부적합품에 대한 특별 채용(특채) 의뢰. 고객 승인 필요 여부 포함.', '["작성","검토","승인"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-03.xlsx'),
  ('B1100-04', '수리 작업 일지', 'B-1100', '부적합품을 수리(리워크)한 작업 기록. 수리 방법·수량·재검사 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-04.xlsx'),
  ('B1100-05', '불량유출 봉쇄 작업표', 'B-1100', '부적합이 고객에게 흘러가지 않도록 재고·운송 중 제품을 봉쇄(선별)한 작업표. 대상 LOT·선별 수량·결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, '{
  "blocks": [
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a1" }, { "fieldKey": "a4" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a2" }, { "fieldKey": "a3" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "a5" }, { "fieldKey": "a6" }, { "fieldKey": "a7" } ] },
    { "type": "full", "fieldKey": "a8" },
    { "type": "section", "title": "불량유출 봉쇄 범위" },
    { "type": "full", "fieldKey": "b1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "b2" }, { "fieldKey": "c1" } ] },
    { "type": "section", "title": "봉쇄 방법 (분류·식별)" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "c2" }, { "fieldKey": "c3" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "c4" }, { "fieldKey": "c5" } ] }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-05.xlsx'),
  ('B1100-06', '폐기보고서', 'B-1100', '폐기 처리할 부적합품의 품번·수량·사유·승인을 적는 보고서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-06.xlsx'),
  ('B1100-07', '품질문제 발생 신속 대응 계통도', 'B-1100', '열람형 — 품질 문제 발생 시 보고·대응 순서를 그린 계통도와 신속대응 조직 연락망.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('B1100-08', '부적합품 처리 기준(가로)', 'B-1100', '열람형 — 부적합품 처리(재작업·특채·폐기) 판단 기준 도해.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('B1100-09', '특채 관리대장', 'B-1100', '특채 의뢰서의 번호·품번·특채 종류·고객 승인 여부·종결을 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-09.xlsx'),
  ('B1100-10', '폐기보고 관리대장', 'B-1100', '폐기보고서의 번호·품번·수량·승인·폐기 완료를 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-10.xlsx'),
  ('B1100-11', '부적합 보관장 관리 대장', 'B-1100', '부적합품 보관장(격리 구역)에 들어오고 나간 품목을 관리하는 대장. 격리 → 처리 결정까지의 흐름을 보여 줍니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-11.xlsx'),
  ('B1100-12', '리크·리워크 이력대장', 'B-1100', '기밀(리크) 불량의 발생부터 리워크·재검사·판정까지 추적하는 이력대장. 리워크 LOT에는 식별 표시(-R)를 붙입니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '2_9,6_10', 'templates/standard/B1100-12.xlsx'),
  ('B1100-13', '부적합품 처리대장', 'B-1100', '부적합(추정)품의 격리~재검사~폐기/리워크/복귀 수량을 대사하는 처리대장. 들어온 수량과 나간 수량이 맞아야 합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '6_6', 'templates/standard/B1100-13.xlsx'),
  ('B2100-01', '시정/예방조치 요구서', 'B-2100', '부적합 사항에 대한 시정 또는 예방조치를 요구. IATF §10.2.3~10.2.6.', '["담당","팀장","사업부장","부사장","대표이사"]', 'B2100-03', '상세 개선 대책을 수립합니다', 'B1100-01', '{
  "blocks": [
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "s1" }, { "fieldKey": "s2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "s3" }, { "fieldKey": "s4" } ] },
    { "type": "grid", "columns": 1, "cells": [ { "fieldKey": "s5" } ] },
    { "type": "section", "title": "부적합 내용" },
    { "type": "full", "fieldKey": "s6" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "s7" }, { "fieldKey": "s8" } ] },
    { "type": "section", "title": "조치 내용 (수신처 작성)" },
    { "type": "full", "fieldKey": "s9" },
    { "type": "full", "fieldKey": "s10" }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-01.xlsx'),
  ('B2100-02', '시정 및 예방조치 등록대장', 'B-2100', '시정·예방조치 요구서의 발행~완료~유효성 확인을 번호로 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-02.xlsx'),
  ('B2100-03', '개선 대책서', 'B-2100', '고객 불만·내부 부적합에 대한 개선 대책서. 현상·원인(5-Why)·대책·재발 방지·유효성 확인을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, 'B2100-01', '{
  "blocks": [
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a1" }, { "fieldKey": "a2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a3" }, { "fieldKey": "a4" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "a5" }, { "fieldKey": "a6" }, { "fieldKey": "a7" } ] },
    { "type": "section", "title": "문제 정의" },
    { "type": "full", "fieldKey": "p1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "p2" }, { "fieldKey": "p3" } ] },
    { "type": "full", "fieldKey": "p4" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "p5" }, { "fieldKey": "p6" } ] },
    { "type": "section", "title": "개선 대책 (8D)" },
    { "type": "full", "fieldKey": "d1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "d2" }, { "fieldKey": "d3" } ] },
    { "type": "section", "title": "개선 내용 및 유효성 확인" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "g1" }, { "fieldKey": "g2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "v1" }, { "fieldKey": "v3" } ] },
    { "type": "full", "fieldKey": "v2" }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-03.xlsx'),
  ('B2100-04', '장기테마', 'B-2100', '장기 개선 테마의 추진 일정 관리표. 월별 진행 상태와 완료 기준을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-04.xlsx'),
  ('B2100-05', '즉실천항목', 'B-2100', '일일 품질(신속대응) 회의에서 나온 즉시 실천 항목의 관리표. 담당·기한·완료 여부를 추적합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-05.xlsx'),
  ('B2100-06', '금형 진행사항 점검', 'B-2100', '금형 관련 개선·수리 진행 사항 점검표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-06.xlsx'),
  ('B2100-07', '설비점검 진행사항', 'B-2100', '설비 점검에서 나온 개선 사항의 진행 상태 점검표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-07.xlsx'),
  ('B2100-08', '4M변경 내역 및 적용일자 관리', 'B-2100', '4M 변경 내역과 실제 적용일자를 관리하는 표. 변경 의뢰서와 번호로 연결됩니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-08.xlsx'),
  ('B2100-09', '공정개선 T O 진행사항 점검', 'B-2100', '공정 개선 과제(T/O)의 진행 상황 점검표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-09.xlsx'),
  ('B2100-10', '용접 개선 T O 진행사항 점검', 'B-2100', '용접 공정 개선 과제(T/O)의 진행 상황 점검표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-10.xlsx'),
  ('B2100-11', '고객사 불량 유효성 검증 관리대장', 'B-2100', '고객사 불량에 대한 대책의 유효성(재발 여부)을 일정 기간 추적하는 관리대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-11.xlsx'),
  ('B2100-12', '유효성 점검 체크시트', 'B-2100', '개선 대책이 현장에 정착했는지 확인하는 유효성 점검 체크시트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-12.xlsx'),
  ('B2200-05', '품질실적 월보', 'B-2200', '월별 품질 실적 보고(공정·고객·외주 PPM). 연간 목표 대비 달성률을 보여 주며 경영검토 입력 자료입니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', '6_7', 'templates/standard/B2200-05.xlsx'),
  ('B2300-01', '정성품질 CFT 업무 분장', 'B-2300', '열람형 — 정성품질(고객 품질 프로그램) 활동의 조직별 역할 분장표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, NULL),
  ('B2300-02', '정성품질 취합 대장', 'B-2300', '정성품질 점검에서 나온 의견을 모아 관리하는 취합 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-02.xlsx'),
  ('B2300-03', '정성품질 점검 체크시트', 'B-2300', '고객 정성품질 유도방안 점검 체크시트(갑지). 점검 현황과 항목별 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-03.xlsx'),
  ('B2300-04', '문제점 및 개선 제안서', 'B-2300', '현장에서 발견한 문제점과 개선 제안을 적는 제안서. 분류·사진·개선안을 담습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-04.xlsx'),
  ('B2300-05', '정성품질 개선 타당성 검토', 'B-2300', '개선 제안의 타당성을 검토한 회의록. 검토 문항에 YES/NO로 답합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-05.xlsx'),
  ('B2300-06', '유효성 평가 보고서', 'B-2300', '개선 실시 후 효과를 평가한 보고서. 개선 전/후 비교와 합격/불합격 판정을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-06.xlsx'),
  ('B2300-07', '인라인 공정불량 사례 시트', 'B-2300', '관리 부실로 생긴 공정 불량 사례를 기록한 시트. 재발 방지 교육 자료로 씁니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-07.xlsx'),
  ('B2300-08', '정성품질 순회 점검 시트', 'B-2300', '정성품질 순회 점검 시트. 작업환경~재발방지 16개 항목을 라인별로 점검합니다.', '["담당","사업부장","대표이사"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-08.xlsx'),
  ('D-1100', '제품 특성 안전관리 규정', 'D-1100', '「제품 특성 안전관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, NULL),
  ('D-2100', '안전보건관리규정', 'D-2100', '「안전보건관리규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('D-2101', '작업장 안전관리 지침', 'D-2101', '「작업장 안전관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('D1100-01', '안전 사고 발생보고서', 'D-1100', '안전 사고 발생 시 작성하는 보고서. 사고 경위(6하원칙)·원인·조치를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-01.xlsx'),
  ('D1100-02', '연간 제품안전교육 계획서', 'D-1100', '연간 제품안전 교육 계획서. 월별 계획(○)과 실적(●)을 표시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-02.xlsx'),
  ('D1100-03', '제품 안전교육 보고서', 'D-1100', '제품안전(PSCR) 교육을 실시한 뒤 쓰는 보고서. 목적·내용·참석자·효과성을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-03.xlsx'),
  ('D1100-04', '공정 안전점검 연간 계획_실적', 'D-1100', '공정 안전점검의 연간 계획과 실적(점검·지적·개선 완료·유효성)을 월별로 적는 표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-04.xlsx'),
  ('D1100-05', '공정 안전점검 체크시트', 'D-1100', '공정 안전점검 체크시트. 가스·전기·시설물 등 항목별 점검 결과와 특이사항을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-05.xlsx'),
  ('D1100-06', '공정 안전점검 개선대책', 'D-1100', '안전점검에서 지적된 사항의 개선 대책서. 개선 전/후 사진과 완료일을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-06.xlsx'),
  ('E-1100', '환경 리스크 평가 규정', 'E-1100', '「환경 리스크 평가 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6', NULL, NULL),
  ('E-1101', '환경측면 파악 및 리스크 평가표 작성지침', 'E-1101', '「환경측면 파악 및 리스크 평가표 작성지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6', NULL, NULL),
  ('E-2100', '안전보건,환경 법규관리 규정', 'E-2100', '「안전보건,환경 법규관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, NULL),
  ('E-3100', '환경운영관리 규정', 'E-3100', '「환경운영관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3101', '작업환경관리 지침', 'E-3101', '「작업환경관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3102', '소음진동 관리 지침', 'E-3102', '「소음진동 관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3103', '폐기물 관리 지침', 'E-3103', '「폐기물 관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3104', '유해화학물질 관리 지침', 'E-3104', '「유해화학물질 관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3105', '대기관리 지침', 'E-3105', '「대기관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3106', '수질관리 지침', 'E-3106', '「수질관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3107', '소방시설 관리 지침', 'E-3107', '「소방시설 관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3108', '에너지 관리 지침', 'E-3108', '「에너지 관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-5100', '감시 및 측정관리 규정', 'E-5100', '「감시 및 측정관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, NULL),
  ('F1100-01', '연간 사내외 교육훈련 계획서', 'F-1100', '연간 사내외 교육훈련 계획서. 과정별 월 일정을 적고 실적을 덧써 계획 대비 실적을 보입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-01.xlsx'),
  ('F1100-02', '교육 이수 보고서', 'F-1100', '외부 교육을 다녀온 뒤 내는 이수 보고서. 과정·기간·내용과 전달 교육 실시 여부를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-02.xlsx'),
  ('F1100-04', '지식 관리표', 'F-1100', '조직 지식(노하우·교훈)을 프로세스별로 정리한 관리표(IATF 7.1.6).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-04.xlsx'),
  ('F1100-05', '사내교육 관리대장', 'F-1100', '사내 교육 실시 이력 대장. 일자·교육명·강사·참석자를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-05.xlsx'),
  ('F1100-06', '사내 교육 보고서', 'F-1100', '사내 교육 1회분 보고서. 교육 내용·참석 인원·사진을 첨부합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-06.xlsx'),
  ('F1101-01', '신임 교육 계획서', 'F-1101', '신규 입사자·보직자의 교육 계획서. 과목·담당·기간을 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1101-01.xlsx'),
  ('F1101-02', '신임 교육 일지', 'F-1101', '신규 입사자 교육의 일별 실시 기록.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1101-02.xlsx'),
  ('F1101-03', '신규입사자 온보딩 체크리스트(오퍼레이터)', 'F-1101', '신규 작업자(오퍼레이터) 온보딩 체크리스트. 안전·작업표준·품질 기본을 단계별로 확인합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '관리팀', '7.2', NULL, 'templates/standard/F1101-03.xlsx'),
  ('F1101-04', '신규입사자 온보딩 체크리스트(관리자)', 'F-1101', '신규 관리자 온보딩 체크리스트. 규정·시스템·책임 범위를 단계별로 확인합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '관리팀', '7.2', NULL, 'templates/standard/F1101-04.xlsx'),
  ('F2100-01', '사내 자격 관리대장', 'F-2100', '사내 자격(공정 작업자·검사원·내부심사원 등) 보유자 관리대장. 자격 번호·부여일·유효일을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-01.xlsx'),
  ('F2100-02', '사내 자격 인증 카드', 'F-2100', '자격 보유자 개인의 인증 카드. 자격 종류와 유효 기간을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-02.xlsx'),
  ('F2100-03', '사내 자격 인증서', 'F-2100', '자격 인증서(수여용).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-03.xlsx'),
  ('F2100-04', '자격인증 변경 요청서', 'F-2100', '자격 신규·갱신·취소를 요청하는 변경 요청서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-04.xlsx'),
  ('F2100-05', '공정면허 이론평가서', 'F-2100', '공정면허 이론평가서 묶음(1안·2안) — 실제 작성은 F2100-05-01 / F2100-05-02.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-05.xlsx'),
  ('F2100-05-01', '공정면허 이론평가서 1안', 'F-2100', '공정 작업자 자격 이론평가서 1안(10문항). 응시 정보와 점수를 적고 답안은 시트에 기입합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-05-01.xlsx'),
  ('F2100-05-02', '공정면허 이론평가서 2안', 'F-2100', '공정 작업자 자격 이론평가서 2안(10문항). 1안과 교대로 출제합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-05-02.xlsx'),
  ('F2100-06', '공정면허 실기평가서', 'F-2100', '공정 작업자 자격 실기평가서. 실제 작업 수행을 항목별로 채점합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-06.xlsx'),
  ('F2100-07', '숙련도_다기능 평가 계획', 'F-2100', '숙련도·다기능 평가의 연간 계획. 평가 항목·주기·월별 계획/실적을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-07.xlsx'),
  ('F2100-08', '숙련도 평가표', 'F-2100', '작업자 숙련도 평가표. 공정별 숙련 등급을 매깁니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-08.xlsx'),
  ('F2100-09', '작업자 현장 직무 현황', 'F-2100', '작업자별 현재 배치 공정과 직무 현황표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-09.xlsx'),
  ('F2100-10', '작업자 숙련도 CHECK SHEET', 'F-2100', '작업자 숙련도 체크시트(매트릭스 채점형). 대상자·특이사항을 적고 점수는 시트에서 계산합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-10.xlsx'),
  ('F2100-11', '자격 인증 교육 및 평가서', 'F-2100', '자격 인증 교육 실시와 평가(이론·실기 점수) 기록. 합격 기준을 함께 명시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-11.xlsx'),
  ('F2100-12', '공정별 전담자 및 대체자 관리기준', 'F-2100', '공정별 전담자와 대체자를 정한 관리 기준. 결원 시 누가 대신하는지 보여 줍니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-12.xlsx'),
  ('F2100-13', '공정면허 자격인증 평가서(종합)', 'F-2100', '자격인증 종합 평가서. 명부별 R&R·실기·이론·근속을 종합해 등급을 판정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-13.xlsx'),
  ('F2100-14', '공정면허 자격인증평가(갑지)', 'F-2100', '공정면허 자격인증 평가서(갑지). 평가 개요와 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-14.xlsx'),
  ('F2100-15', '공정 자격인증카드_공정 게시용', 'F-2100', '공정 게시용 자격 인증 카드. 해당 공정에 자격자가 배치됐음을 현장에서 보여 줍니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-15.xlsx'),
  ('H-1100', '계약검토 규정', 'H-1100', '「계약검토 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, NULL),
  ('H1100-01', '제조타당서 검토서', 'H-1100', '신규 수주 전 제조 타당성(설비·공정·납기·원가)을 검토한 검토서. 계약검토의 핵심 증거입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-01.xlsx'),
  ('H1100-02', '개발의뢰 접수대장', 'H-1100', '고객 개발 의뢰의 접수 번호·일자·품번·담당을 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-02.xlsx'),
  ('H1100-03', '원가계산서', 'H-1100', '견적·수주용 원가계산서. 재료비·가공비·경비 항목을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-03.xlsx'),
  ('H1100-04', '원단위 원가분석', 'H-1100', '제품 1개당 원단위(재료·공수) 분석표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-04.xlsx'),
  ('H2100-02', '월 납품량 분석 보고서', 'H-2100', '월 납품량 분석 보고서. 수주·출고·납입률을 일자별로 집계합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, 'templates/standard/H2100-02.xlsx'),
  ('H2100-03', '일일 납품 실적 보고서(', 'H-2100', '일일 납품 실적 보고서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, 'templates/standard/H2100-03.xlsx'),
  ('H3100-01', '연간 고객만족도 모니터링', 'H-3100', '연간 고객만족도 모니터링 표. 고객사별 지표(납기·품질·대응)를 월별로 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-01.xlsx'),
  ('H3100-02', '고객만족도 조사 시행 계획서', 'H-3100', '고객만족도 조사의 대상·방법·일정 계획서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-02.xlsx'),
  ('H3100-03', '고객만족도 평가서(설문지)', 'H-3100', '고객에게 보내는 만족도 평가 설문지.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-03.xlsx'),
  ('H3100-04', '종업원 만족도 조사 설문지', 'H-3100', '종업원 만족도 조사 설문지.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-04.xlsx'),
  ('H3100-05', '종업원 만족도 조사결과 보고서', 'H-3100', '종업원 만족도 조사 결과 보고서. 배포/회수 수와 집계 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-05.xlsx'),
  ('H3100-06', '종업원 동기부여 계획서', 'H-3100', '종업원 동기부여(포상·복지·환경) 연간 계획서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-06.xlsx'),
  ('H3100-07', '종업원 동기부여 실적평가서', 'H-3100', '종업원 동기부여 실적 평가서. 계획 대비 추진 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-07.xlsx'),
  ('H3200-01', '고객불만 접수 대응 현황 보고서', 'H-3200', '고객 불만의 접수~대응~결론 현황을 한 표로 관리하는 대장. 대응 시간과 경비를 같이 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/H3200-01.xlsx'),
  ('H3200-02', '고객불만 대응 조치 결과 보고서', 'H-3200', '고객 불만 1건의 대응 조치 결과 보고서(8D 형식). 현상·원인·대책·유효성을 적어 고객에게 회신합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, '{
  "blocks": [
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "a1" }, { "fieldKey": "a2" }, { "fieldKey": "a3" } ] },
    { "type": "section", "title": "1. 고객불만 접수 이력" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "r1" }, { "fieldKey": "r2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "r3" }, { "fieldKey": "r4" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "r5" }, { "fieldKey": "r6" } ] },
    { "type": "section", "title": "2. 고객불만 내용" },
    { "type": "full", "fieldKey": "m1" },
    { "type": "section", "title": "3. 고객불만 대응 결과" },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "g1" }, { "fieldKey": "g2" }, { "fieldKey": "g3" } ] },
    { "type": "full", "fieldKey": "g4" },
    { "type": "section", "title": "4. 고객불만 대응 조사 결과" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "i1" }, { "fieldKey": "i2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "i3" }, { "fieldKey": "i4" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "i5" }, { "fieldKey": "i6" } ] },
    { "type": "section", "title": "5. 협의 · 최종 결론" },
    { "type": "full", "fieldKey": "c1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "c2" } ] },
    { "type": "full", "fieldKey": "c3" }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/H3200-02.xlsx'),
  ('J-1100', '개발업무 규정', 'J-1100', '「개발업무 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, NULL),
  ('J-1101', '공정FMEA 작성 및 관리 지침', 'J-1101', '「공정FMEA 작성 및 관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '6,8', NULL, NULL),
  ('J-2100', '양산부품 승인업무 규정', 'J-2100', '「양산부품 승인업무 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('J-3100', '4M 변경관리 규정', 'J-3100', '「4M 변경관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, NULL),
  ('J-4100', '도면관리 규정', 'J-4100', '「도면관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, NULL),
  ('J-4200', '도면 부품 일치성 점검 지침', 'J-4200', '「도면 부품 일치성 점검 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('J1100-01', '개발일정 계획서', 'J-1100', '신제품 개발 일정 계획서(APQP 단계별). 마일스톤과 담당을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-01.xlsx'),
  ('J1100-02', '공정흐름도', 'J-1100', '공정흐름도. 공정 순서와 특별특성(KPC)을 표시하며 관리계획서·FMEA와 공정번호가 같아야 합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-02.xlsx'),
  ('J1100-03', '특별특성 목록표', 'J-1100', '특별특성(제품·공정) 목록표. 고객 지정 특성과 사내 지정 특성을 구분해 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-03.xlsx'),
  ('J1100-04', '부품개발 요청서', 'J-1100', '고객/내부에서 부품 개발을 요청하는 요청서. 요구사항·납기·수량을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-04.xlsx'),
  ('J1100-05', '제품 품질계획요약 및 완료확인서', 'J-1100', '제품 품질계획(APQP) 단계별 산출물 완료 여부 요약·확인서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-05.xlsx'),
  ('J1100-06', '개발품 TRY-OUT 일정 계획서', 'J-1100', '개발품 시험 생산(TRY-OUT) 일정 계획서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-06.xlsx'),
  ('J1100-07', '개발품 TRY-OUT 완료 보고서', 'J-1100', '개발품 시험 생산 완료 보고서. 결과와 문제점·조치를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-07.xlsx'),
  ('J1100-08', '납입용기 설정서', 'J-1100', '납입 용기(포장) 사양 설정서. 용기 종류·적재 수량·라벨을 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-08.xlsx'),
  ('J1100-09', '제조타당성 확인서', 'J-1100', '제조 타당성 확인서. 설계 요구사항을 현 설비·공정으로 만들 수 있는지 확인합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-09.xlsx'),
  ('J1100-10', '제품 법_규제 요구사항 목록표', 'J-1100', '제품에 적용되는 법규·규제 요구사항 목록표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-10.xlsx'),
  ('J1100-11', 'PM 및 MDT 선정기준', 'J-1100', '프로젝트 매니저(PM)와 다기능팀(MDT) 선정 기준.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-11.xlsx'),
  ('J1100-12', '에스켈레이션 기준', 'J-1100', '문제 발생 시 보고 단계(에스컬레이션) 기준.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-12.xlsx'),
  ('J1100-13', '양산이관기준', 'J-1100', '개발에서 양산으로 넘길 때의 이관 판정 기준.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-13.xlsx'),
  ('J1100-14', '고객 접수 도면 검토서', 'J-1100', '고객에게 받은 도면을 검토한 검토서. 치수·공차·특별특성·제조 가능성을 항목별로 확인합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-14.xlsx'),
  ('J1101-01', '공정 FMEA 4판 SHEET', 'J-1101', '공정 FMEA(4판) 시트. 공정별 고장형태·영향·원인·예방/검출 관리와 권고 조치를 적습니다. 관리계획서와 짝을 이룹니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '6,8', NULL, 'templates/standard/J1101-01.xlsx'),
  ('J1102-01', '관리계획서 1판 표지 ( 갑)', 'J-1102', '관리계획서 표지(갑지). 품번·차종·상호기능팀·개정 이력을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J1102-01.xlsx'),
  ('J1102-02', '관리계획서 특별특성', 'J-1102', '관리계획서의 특별특성 목록. 공정흐름도·FMEA의 KPC와 일치해야 합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J1102-02.xlsx'),
  ('J1102-03', '관리계획서 체크리스트', 'J-1102', '관리계획서 작성 내용을 AIAG 21문항으로 자체 점검하는 체크리스트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J1102-03.xlsx'),
  ('J1103-01', '작업표준서', 'J-1103', '작업표준서. 공정별 작업 순서·조건(수치)·자주검사·안전·이상 시 조치를 적어 현장에 게시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/J1103-01.xlsx'),
  ('J3100-01', '4M 변경 의뢰서', 'J-3100', '4M(사람·설비·재료·방법) 변경 의뢰서. 변경 전/후·사유·품질 영향·검증 계획을 적고 고객 통보 필요 여부를 판단합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-01.xlsx'),
  ('J3100-02', '사양변경접수대장', 'J-3100', '고객 사양 변경 접수 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-02.xlsx'),
  ('J3100-03', '4M 변경 관리대장', 'J-3100', '4M 변경 의뢰의 접수~검증~적용~고객 승인을 관리하는 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-03.xlsx'),
  ('J3100-04', '4M변경 판단기준', 'J-3100', '열람형 — 4M 변경 판단 기준표. 변경 유형별 고객 통보·승인 필요 여부를 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, NULL),
  ('J3100-05', '변경점 관리 계획 대비 실적', 'J-3100', '변경점 관리의 계획 대비 실적표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-05.xlsx'),
  ('J3100-06', '변경점 점검 조직도', 'J-3100', '변경점 발생 시 점검 조직과 역할을 그린 조직도.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-06.xlsx'),
  ('J3100-07', '4M 변경점 관리 점검 C SHEET', 'J-3100', '4M 변경점 관리 점검 체크시트. 변경 후 초도품 검증 항목을 확인합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-07.xlsx'),
  ('J3100-08', '4M 변경 마스터리스트', 'J-3100', '4M·설계 변경 마스터리스트. 전 변경 건을 번호로 모아 추적합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', '6_2', 'templates/standard/J3100-08.xlsx'),
  ('J4100-01', '도면관리대장', 'J-4100', '도면 접수·배포·개정·폐기를 관리하는 대장. 현장 도면이 최신 Rev인지의 근거입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J4100-01.xlsx'),
  ('J4200-01', '도면 일치성 점검 체크시트', 'J-4200', '도면과 실제 부품의 일치성 점검 체크시트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J4200-01.xlsx'),
  ('K1100-01', '원자재 입고 요청서', 'K-1100', '원자재 입고(발주) 요청서. 품목·규격·수량·납기를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1100-01.xlsx'),
  ('K1100-02', '원소재 생산 의뢰서', 'K-1100', '원소재 생산 의뢰서(외주 소재 가공 의뢰).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1100-02.xlsx'),
  ('K1100-07', '기본공급 계약서', 'K-1100', '열람형 — 협력업체와의 기본 공급 계약서(조문). 체결은 서면·인감으로 합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K1100-08', '클레임 보상협정서', 'K-1100', '열람형 — 클레임 보상 협정서(조문).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K1100-09', '품질 보증 협정서', 'K-1100', '열람형 — 품질 보증 협정서(조문). 협력업체 품질 책임 범위를 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K1100-10', '원재료 법_규제 요구사항 목록표', 'K-1100', '원재료에 적용되는 법규·규제(환경 유해물질 등) 요구사항 목록표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1100-10.xlsx'),
  ('K1200-01', '①협력업체 등록대장', 'K-1200', '협력업체 등록대장. 업체 코드·품목·등록일·등급을 관리합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-01.xlsx'),
  ('K1200-02', '②승인 자재 목록 (AVL. AML)', 'K-1200', '승인된 자재·공급사 목록(AVL/AML). 승인 외 공급사 구매를 막는 근거입니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-02.xlsx'),
  ('K1200-03', '③협력업체 사후 평가 계획서', 'K-1200', '협력업체 사후(정기) 평가 계획서. 평가 대상·주기·항목을 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-03.xlsx'),
  ('K1200-04', '④업체 실태 조사서', 'K-1200', '신규 협력업체 실태 조사서. 현장 방문 결과를 항목별로 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-04.xlsx'),
  ('K1200-04-01', '타사업부 실적,체제 평가 계획서', 'K-1200', '협력업체 실적·체제 평가 계획서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-04-01.xlsx'),
  ('K1200-05', '⑤협력업체 체제 평가표', 'K-1200', '협력업체 체제 평가표. 품질 시스템·공정·납기를 점수화합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-05.xlsx'),
  ('K1200-06', '협력사 월별 모니터링', 'K-1200', '협력사 월별 모니터링 표. 납기·품질(PPM)·대응 지표를 월별로 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-06.xlsx'),
  ('K1200-07', '외주 ISIR·검사협정 접수대장', 'K-1200', '외주 업체의 ISIR(초도품 검사)·검사협정서 접수·개정 이력 대장. 심사에서 자주 묻는 항목입니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-07.xlsx'),
  ('K2100-01', '장기재고관리 현황', 'K-2100', '장기 재고(일정 기간 미사용) 현황표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-01.xlsx'),
  ('K2100-04', '재고조사표', 'K-2100', '재고 실사표. 실사 기준일 기준 품목별 수량·중량·보관 장소를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-04.xlsx'),
  ('K2100-05', '장기 재고 점검대장', 'K-2100', '장기 재고의 점검·처리(사용·폐기) 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-05.xlsx'),
  ('K2100-06', '선입선출 관리 기준서', 'K-2100', '선입선출(FIFO) 관리 기준서. 어떻게 앞 LOT를 먼저 꺼내게 하는지(위치·색·표시)를 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-06.xlsx'),
  ('K2100-07', '장기 재고 관리 기준서', 'K-2100', '열람형 — 장기 재고 판정·처리 기준서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K2100-08', '소모품 월소요량 및 안전재고', 'K-2100', '소모품 월 소요량과 안전 재고 기준표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-08.xlsx'),
  ('K2100-09', '소모품 사양 및 공급처 지정 현황', 'K-2100', '소모품 사양과 지정 공급처 현황표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-09.xlsx'),
  ('K2100-10', '자재 보관장 점검표·Lay-Out', 'K-2100', '자재 보관장 점검표와 배치도(Lay-Out). 보관 구역별 식별·FIFO·환경을 점검합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', '5_2', 'templates/standard/K2100-10.xlsx'),
  ('L-4100', '통계적 기법적용 규정', 'L-4100', '「통계적 기법적용 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, NULL),
  ('L-4101-01', 'SPC 평가표', 'L-4101', 'SPC 평가표(Xbar-R·Cpk 계산기). 측정 데이터를 넣으면 관리도와 공정능력이 계산됩니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L-4101-01.xlsx'),
  ('L1100-01', '설비제작 사양서', 'L-1100', '신규 설비 제작 사양서. 요구 성능·안전·검수 조건을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-01.xlsx'),
  ('L1100-02', '설비제작 진행 체크리스트', 'L-1100', '설비 제작 진행 단계별 체크리스트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-02.xlsx'),
  ('L1100-03', '입회검수 체크시트', 'L-1100', '설비 입회 검수 체크시트. 지적사항과 개선 완료를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-03.xlsx'),
  ('L1100-04', '설비 TRY-OUT 결과 보고서', 'L-1100', '설비 시운전(TRY-OUT) 결과 보고서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-04.xlsx'),
  ('L1100-05', '납품 및 시운전(검수) 확인서', 'L-1100', '설비 납품·시운전 검수 확인서. 공급자 정보와 품목을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-05.xlsx'),
  ('L1100-06', '설비고장 조치 보고서', 'L-1100', '설비 고장 발생 시 조치 보고서. 고장 내용·원인·조치·재발 방지를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-06.xlsx'),
  ('L1100-07', '설비 일상 점검표', 'L-1100', '설비 일상 점검표. 작업 전 점검 항목을 날마다 확인하고 서명합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-07.xlsx'),
  ('L1100-08', '설비 리스트', 'L-1100', '보유 설비 리스트. 설비 번호·명칭·위치·도입일을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-08.xlsx'),
  ('L1100-09', '설비 이력카드', 'L-1100', '설비 1대의 이력카드. 기본 정보와 수리·보전 이력을 누적합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-09.xlsx'),
  ('L1100-10', '제조설비 관리대장(갑지)', 'L-1100', '제조 설비 관리대장(갑지). 설비별 관리 등급과 점검 주기를 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-10.xlsx'),
  ('L1100-11', '년간 예방보전 계획서', 'L-1100', '연간 예방보전(PM) 계획서. 설비별 점검 주기와 월별 계획/실시를 표시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-11.xlsx'),
  ('L1100-12', '월간설비 정기 점검 계획서', 'L-1100', '월간 설비 정기점검 계획서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-12.xlsx'),
  ('L1100-13', '테마별 설비 정기점검 계획서(갑지)', 'L-1100', '테마별 설비 정기점검 계획서(갑지).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-13.xlsx'),
  ('L1100-14', '중요설비 체크리스트', 'L-1100', '중요 설비 체크리스트. 설비별 평가 항목 점수로 중요도 등급을 매깁니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-14.xlsx'),
  ('L1100-15', '업무 일지', 'L-1100', '설비 부서 업무 일지. 당일 작업·영선 활동·다음 날 예정을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-15.xlsx'),
  ('L1100-16', '스페어파트 관리대장', 'L-1100', '스페어 파트 관리대장. 부품별 적정 재고·현재고·구매처를 관리합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-16.xlsx'),
  ('L1100-17', '고정자산 폐기 품의서', 'L-1100', '고정자산(설비) 폐기 품의서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-17.xlsx'),
  ('L1100-18', '풀프로프 설비 점검 일지', 'L-1100', '풀프루프(F/P) 설비 점검 일지. 설비별 작동 여부를 정기 점검합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-18.xlsx'),
  ('L1100-19', '설비 이관 교육결과 보고서', 'L-1100', '설비 이관 시 실시한 교육 결과 보고서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-19.xlsx'),
  ('L1100-20', 'F_P 이상발생 점검 체크시트', 'L-1100', '풀프루프 장치 이상 발생 시 점검 체크시트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-20.xlsx'),
  ('L1100-21', '설비 데이터 빽업 기준서', 'L-1100', '설비 데이터(프로그램·파라미터) 백업 기준서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-21.xlsx'),
  ('L1100-22', '설비 데이터 빽업 관리대장', 'L-1100', '설비 데이터 백업 실시 관리대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-22.xlsx'),
  ('L1100-23', '설비관리 기준서', 'L-1100', '설비 관리 기준서. 점검 주기·책임·기록 방법을 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-23.xlsx'),
  ('L1100-24', '설비능력 지수표', 'L-1100', '설비능력 지수표. 설비별 가동률·능력 지수를 산출합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-24.xlsx'),
  ('L1100-25', '금형 점검 체크시트(일상/정기/보관)', 'L-1100', '금형 점검 체크시트(일상·정기·보관). 금형 번호별 점검 결과를 월 단위로 기록합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', '4_1,4_2,4_3,4_4,4_5', 'templates/standard/L1100-25.xlsx'),
  ('L1200-01', '치공구 관리대장', 'L-1200', '치공구 관리대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-01.xlsx'),
  ('L1200-02', '치공구 이력카드', 'L-1200', '치공구 이력카드.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-02.xlsx'),
  ('L1200-03', '지그 관리대장', 'L-1200', '지그 관리대장. 지그 번호·적용 공정·보관 위치를 관리합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-03.xlsx'),
  ('L1200-04', '지그 이력카드', 'L-1200', '지그 이력카드. 제작·수리·검사 이력을 누적합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-04.xlsx'),
  ('L1200-05', '지그 및 치공구 검사 성적서', 'L-1200', '지그·치공구 검사 성적서. 검사 항목별 기준·측정치·판정을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-05.xlsx'),
  ('L1200-06', 'CF 점검기준서', 'L-1200', '체크 픽스처(C/F) 점검 기준서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-06.xlsx'),
  ('L1200-07', 'CF 점검 시트', 'L-1200', '체크 픽스처(C/F) 점검 시트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-07.xlsx'),
  ('L1200-08', '지그계약서', 'L-1200', '열람형 — 지그 제작 계약서(조문).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, NULL),
  ('L1200-09', '지그 사용대차 계약서', 'L-1200', '열람형 — 지그 사용대차 계약서(조문).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, NULL),
  ('L1200-10', '대여자산 관리대장', 'L-1200', '고객·협력사에서 빌린 대여 자산(지그·금형) 관리대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-10.xlsx'),
  ('L1200-11', '지그 및 금형 보관 위치 식별표', 'L-1200', '지그·금형 보관 위치 식별표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-11.xlsx'),
  ('L1200-12', '지그·치공구 점검 체크시트', 'L-1200', '지그·치공구 점검 체크시트. 지그 번호별 일상 점검 결과를 월 단위로 기록합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', '3_3,3_7', 'templates/standard/L1200-12.xlsx'),
  ('L2100-01', '수입검사표준', 'L-2100', '수입검사 표준. 원소재·구매품의 품번별 검사 항목·기준·방법을 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2100-01.xlsx'),
  ('L2100-05', '공정 순회검사(패트롤) 시트', 'L-2100', '공정 순회검사(패트롤) 시트. 순회 시 공정별 조건·외관을 점검한 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2100-05.xlsx'),
  ('L2100-07', '수입검사 관리대장', 'L-2100', '수입검사 관리대장. 입고별 검사 결과·판정·합격 여부를 누적합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '2_2', 'templates/standard/L2100-07.xlsx'),
  ('L2100-11', '조도관리 측정기록', 'L-2100', '표면 조도(거칠기) 측정 기록. 품번·측정 위치별 측정값과 판정을 적습니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '6_8', 'templates/standard/L2100-11.xlsx'),
  ('L2200-01', '연간 신뢰성 시험 계획서', 'L-2200', '연간 신뢰성 시험 계획서. 시험 항목별 월 계획과 실적을 표시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2200-01.xlsx'),
  ('L2300-01', '한도견본 관리대장', 'L-2300', '한도견본(외관 합부 기준 샘플) 관리대장. 등록·유효기간·연장·폐기를 관리합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-01.xlsx'),
  ('L2300-02', '한도 견본표', 'L-2300', '한도 견본표. 견본 사진과 합부 기준을 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-02.xlsx'),
  ('L2300-03', '한도 견본 기준서', 'L-2300', '한도 견본 운영 기준서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-03.xlsx'),
  ('L2300-04', 'OK_NG MASTER 관리대장', 'L-2300', 'OK/NG 마스터 샘플 관리대장. 검출 장치 점검용 마스터의 등록·유효성을 관리합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-04.xlsx'),
  ('L2300-05', '치구 자체 검교정 계획 및 실적', 'L-2300', '검사 치구 자체 검교정 계획과 실적표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-05.xlsx'),
  ('L2300-06', '치구 관리대장', 'L-2300', '검사 치구 관리대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-06.xlsx'),
  ('L2300-07', '치구 이력카드', 'L-2300', '검사 치구 이력카드.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-07.xlsx'),
  ('L3100-01', '계측기 관리대장', 'L-3100', '계측기 관리대장. 관리번호·규격·교정 주기·다음 교정일을 관리합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-01.xlsx'),
  ('L3100-02', '계측기 이력카드', 'L-3100', '계측기 1대의 이력카드. 교정·수리·점검 이력을 누적합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-02.xlsx'),
  ('L3100-03', '계측기 검교정 계획서', 'L-3100', '연간 계측기 검교정 계획서. 관리번호별 교정 월 계획(○)과 실시(●)를 표시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-03.xlsx'),
  ('L3100-04', '계측기 일상점검표', 'L-3100', '계측기 일상점검표. 사용 전 외관·0점 확인과 이상 시 조치를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-04.xlsx'),
  ('L3100-05', '계측기 관리번호 부여 기준', 'L-3100', '열람형 — 계측기 관리번호 부여 기준.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('L3100-06', '검교정 합부판정 기준', 'L-3100', '열람형 — 검교정 합부 판정 기준(허용 공차·측정 불확도).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('L3101-01', '측정시스템 분석 계획서', 'L-3101', '측정시스템 분석(MSA) 연간 계획서. 계측기별 R&R 실시 시기를 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3101-01.xlsx'),
  ('L3101-02', '계량형 R&R(전산)', 'L-3101', '계량형 Gage R&R 평가 성적서. 측정자 3명×시료 10개로 측정 시스템의 반복성·재현성을 평가합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3101-02.xlsx'),
  ('L4101-01', 'Xbar-R 관리도', 'L-4101', 'Xbar-R 관리도. 측정 데이터를 넣으면 관리한계와 차트가 계산됩니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L4101-01.xlsx'),
  ('L4102-01', '공정능력 평가표', 'L-4102', '개발 단계 공정능력(Pp·Ppk) 평가표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L4102-01.xlsx'),
  ('L4102-02', '양산단계 공정능력 산출', 'L-4102', '양산 단계 공정능력(Cp·Cpk) 산출표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L4102-02.xlsx'),
  ('M-1100', '생산관리 규정', 'M-1100', '「생산관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M-1200', '공정관리 규정', 'M-1200', '「공정관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M-2100', '식별 및 추적성 관리 규정', 'M-2100', '「식별 및 추적성 관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M-3100', '완성품 관리 규정', 'M-3100', '「완성품 관리 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, NULL),
  ('M-4100', '3정 5S활동 규정', 'M-4100', '「3정 5S활동 규정」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, NULL),
  ('M-4200', '조도(Lux) 관리 지침', 'M-4200', '「조도(Lux) 관리 지침」 규정 본문(열람용). 작성 양식이 아니며 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('M1100-02', '설비 비가동시간 관리 대장', 'M-1100', '설비 비가동 시간 관리대장. 비가동 코드·시간·원인을 일별로 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1100-02.xlsx'),
  ('M1100-03', '설비 비가동시간 이력관리 대장', 'M-1100', '설비 비가동 시간 이력 관리대장(월별 누적).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1100-03.xlsx'),
  ('M1100-05', '설비 비가동 주요 코드', 'M-1100', '열람형 — 설비 비가동 주요 코드 정의표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1100-06', '우발사고 및 이상발생 처리 절차서', 'M-1100', '열람형 — 우발 사고·이상 발생 시 처리 절차서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1200-01', '작업지시서', 'M-1200', '작업지시서. 호기·품번·수량·일정을 적어 현장에 지시합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-01.xlsx'),
  ('M1200-02', '열처리작업일보', 'M-1200', '열처리 작업일보. 열처리 공정 보유 시 조건(온도·시간)과 처리 수량을 기록합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-02.xlsx'),
  ('M1200-03', '주,야 인수인계 일지', 'M-1200', '주·야간 조 인수인계 일지. 설비·품질·안전·자재 이슈를 조별로 적어 넘깁니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-03.xlsx'),
  ('M1200-04', '공정,납입용기 관리기준 및 수리이력', 'M-1200', '공정·납입 용기 관리 기준과 수리 이력.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-04.xlsx'),
  ('M1200-05', '낙하품 처리 절차서', 'M-1200', '열람형 — 낙하품 처리 절차서(낙하품은 무조건 격리·검사).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1200-06', '낙하품 처리 관리대장', 'M-1200', '낙하품 처리 관리대장. 발생·격리·검사·처리 결과를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-06.xlsx'),
  ('M1200-07', '셋업품 처리 절차서', 'M-1200', '열람형 — 셋업(초품 조정) 품 처리 절차서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1200-08', '용접장 기준 팁 교환 주기 평가서', 'M-1200', '용접 팁 교환 주기 평가서. 타점 수 대비 팁 마모를 평가해 교환 주기를 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-08.xlsx'),
  ('M1200-09', '공정이동 전표·부자재 대사표', 'M-1200', '공정 이동 전표와 부자재 대사표. 공정 간 이동 수량과 부자재 사용량을 맞춥니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '6_11', 'templates/standard/M1200-09.xlsx'),
  ('M1200-10', '공정 자주검사 CHECK SHEET', 'M-1200', '공정 자주검사 체크시트. 초·중·종품 검사 항목과 측정값을 기록합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '2_7', 'templates/standard/M1200-10.xlsx'),
  ('M1200-11', '특수공정 조건관리 CHECK SHEET', 'M-1200', '특수공정 조건관리 체크시트. 구간별 온도·보조매체 유량·이송 속도 등 조건을 3회/일 기록합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '1_5,3_5', 'templates/standard/M1200-11.xlsx'),
  ('M2100-01', 'LOT관리 기준서', 'M-2100', 'LOT 관리 기준서. LOT 번호 체계·기록 시기·장소·담당을 정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M2100-01.xlsx'),
  ('M2100-02', '원소재및완제품 선입선출 관리기준서', 'M-2100', '열람형 — 원소재·완제품 선입선출 관리 기준서(적재·출하 순서도).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M2100-10', 'LOT 추적성 대장', 'M-2100', 'LOT 추적성 대장. 원자재 LOT → 공정 → 완제품 LOT를 연결해 역추적을 가능하게 합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '5_1', 'templates/standard/M2100-10.xlsx'),
  ('M3100-01', '출하관리대장', 'M-3100', '출하 관리대장. 출하일·품번·LOT·수량·거래처를 적습니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, 'templates/standard/M3100-01.xlsx'),
  ('M3100-05', '완성품·출하검사 성적서', 'M-3100', '완성품·출하검사 성적서. 출하 전 샘플 검사 결과와 판정을 적습니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '2_8', 'templates/standard/M3100-05.xlsx'),
  ('M3100-06', '용기·적재 표준화 기준표', 'M-3100', '용기·적재 표준화 기준표. 품번별 용기·장입 수·적재 단수·식별을 정합니다.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '5_4', 'templates/standard/M3100-06.xlsx'),
  ('M4100-01', '사무용 3정 5S 진단 SHEET', 'M-4100', '사무실 3정5S 진단 시트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-01.xlsx'),
  ('M4100-02', '현장용 3정 5S 진단 SHEET', 'M-4100', '현장 3정5S 진단 시트. 구역별 정리·정돈·청소 상태를 점수화합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-02.xlsx'),
  ('M4100-03', '3정 5S 평가 보고서', 'M-4100', '3정5S 평가 보고서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-03.xlsx'),
  ('M4100-04', '3정 5S 평가지적 및 시정대책서', 'M-4100', '3정5S 평가 지적 사항과 시정 대책서.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-04.xlsx'),
  ('M4100-05', '3정5S 관리 구역도', 'M-4100', '열람형 — 3정5S 관리 구역도.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, NULL),
  ('M4200-01', '조도측정 체크시트', 'M-4200', '작업장 조도(Lux) 측정 체크시트. 측정 위치별 조도를 기록해 기준 이상인지 확인합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/M4200-01.xlsx')
) WHERE EXISTS (SELECT 1 FROM _migrations WHERE status = 'snapshot' LIMIT 1);
