-- ============================================================
-- packs/standard/080_forms_catalog.sql — 양식 카탈로그 — 294종(표준 xlsx 템플릿 238종 = templates/standard/)(체인 302 − 제외 8: 사업부 전용·타사업부 열람형 / 사업부 scope 3종은 SQ 미니멀 정션 참조라 공통 편입) · ④-1 코드 체계 채택 · 이름 접미 정리 · 설명 중립화(NULL 97) · scope '공통' 통일
-- 자동 생성: scripts/gen-pack-standard.mjs (손편집 금지 — 재작성·제외 목록도 생성기에 있음)
-- 근거: 40호 ④ 도장(2026-08-19) · 39호 S3 · 실명 0·회사식별 0(생성기 게이트)
-- ============================================================
INSERT OR IGNORE INTO forms (code, name, reg_code, description, approvals_json, next_form_code, next_form_label, prev_form_code, layout_json, scope, deprecated, deprecated_note, replacement_page, resp_dept, iatf_clause, sq_item_ids, template_path) VALUES
  ('A-2100', '사업계획 운영 규정', 'A-2100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6', NULL, NULL),
  ('A-3100', '회의운영 규정', 'A-3100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, NULL),
  ('A-4101', '관리표준 작성 지침', 'A-4101', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('A-6300', '품질문제 신고포상 규정', 'A-6300', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', NULL, NULL, NULL),
  ('A-8101', '비상상태 대비 및 대응 규정', 'A-8101', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, NULL),
  ('A1100-01', '개인별 업무 분장표', 'A-1100', '사업부 개인별 업무 분장표. 첫 블록(빈 틀)만 추출. 담당 12블록(담당자명+주요업무). 제목·작성자/작성일(라벨 내장 병합)·인원현황 표는 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, 'templates/standard/A1100-01.xlsx'),
  ('A1100-02', '업무분장 변경 신청서', 'A-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, 'templates/standard/A1100-02.xlsx'),
  ('A2200-01', '회의록', 'A-2200', '회의록(갑지). 헤더(회의일자·회의장소·회의구분·주관부서·작성자·회의안건) + 회의참석자 grid(7~11행, 좌/우 2열 — 소속·직급·성명, 확인란은 서명 몫) + 회의내용(13~33행 자유 영역 textarea). 결재란 5단(담당~대표이사) 서명 몫. IATF §5.1 경영검토 연계.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, 'templates/standard/A2200-01.xlsx'),
  ('A2200-02', '경영검토 계획서', 'A-2200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, 'templates/standard/A2200-02.xlsx'),
  ('A2200-03', '경영검토 보고서', 'A-2200', '헤더+검토항목 14블록 grid+검토내용·특기사항.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, 'templates/standard/A2200-03.xlsx'),
  ('A3200-01', '이해관계자 불만 조치대장', 'A-3200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A3200-01.xlsx'),
  ('A3200-02', '이해관계자 불만 조치일지', 'A-3200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A3200-02.xlsx'),
  ('A4100-01', '회사표준관리대장', 'A-4100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-01.xlsx'),
  ('A4100-02', '표준 제개정 신청서', 'A-4100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-02.xlsx'),
  ('A4100-03', '기술표준관리대장', 'A-4100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-03.xlsx'),
  ('A4100-04', '자료관리대장', 'A-4100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-04.xlsx'),
  ('A4100-05', '양식 제개정 신청서', 'A-4100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-05.xlsx'),
  ('A4100-06', '양식등록대장', 'A-4100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A4100-06.xlsx'),
  ('A4200-01', '보존기록목록표', 'A-4200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A4200-01.xlsx'),
  ('A4200-02', '기록분류표', 'A-4200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A4200-02.xlsx'),
  ('A4200-03', '폐기기록 목록표', 'A-4200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/A4200-03.xlsx'),
  ('A5100-01', '내부심사 년간 계획 및 실적', 'A-5100', '작성일·연도 3(3개년 헤더) + 공정심사 분기 12칸(개별) + 시스템심사 grid(17~34행 2행 블록 9 프로세스: 3개년×분기 4 = 12칸 + 피심사부서). 심사구분·CSR·프로세스명 기정의(경영관리~구매업무 P — 9개), 범례(○◐●)·하단 3번 구분(35행~)·결재는 시트 몫. IATF §9.2 3년 주기 전 프로세스 커버.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-01.xlsx'),
  ('A5100-02', '내부심사 실시 계획서', 'A-5100', '갑지 헤더(관리번호·심사구분·심사항목·피심사부서·심사팀장·심사 우선순위 설정) + 심사 점수표 grid 2종(시스템 심사 11행·공정 심사 7행 — 등급 문자 입력 열만, 우측 배점·소계 수식은 시트 몫). 심사일정(a6)은 앱 기록용 — 을지 일정표는 시트 수기(을지 헤더 = 갑지 미러 수식). IATF §9.2 내부심사.', '["팀장","사업부장","사장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-02.xlsx'),
  ('A5100-03', '내부심사(갑지) 보고서', 'A-5100', '내부심사 보고서 — 갑지(시스템 심사) + 을지(공정·제품 심사). 빈 틀(기록값 없음).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-03.xlsx'),
  ('A5100-04', '내부심사(품질,환경,안전) 체크리스트', 'A-5100', '내부심사(품질·환경·안전) 체크리스트 — 문항 구조 기정의. 상단 결과 매트릭스·지원부서는 앱 기입, 팀별 문항 채점은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5100-04.xlsx'),
  ('A5200-03', '내부심사(제조) 체크리스트', 'A-5200', '내부심사(제조) 체크리스트 — 공정 항목 구조 기정의. 첫 블록(갑지)은 앱 기입, 후속 블록은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5200-03.xlsx'),
  ('A5200-04', '내부심사(제품) 체크리스트', 'A-5200', '내부심사(제품) 체크리스트 — 문항·배점 구조 기정의. 헤더 + 중요 치수(Dim) 기록 grid 는 앱 기입, 문항별 채점은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5200-04.xlsx'),
  ('A5200-04-01', '내부심사 성적서', 'A-5200', '내부심사 성적서 — 조·사업부별 생산품 평가 블록 4(서술 기입). 공정·제품 심사 증거용.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/A5200-04-01.xlsx'),
  ('A6100-01', '나의 제안', 'A-6100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6100-01.xlsx'),
  ('A6100-02', '제안관리대장', 'A-6100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6100-02.xlsx'),
  ('A6100-03', '제안종합현황', 'A-6100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6100-03.xlsx'),
  ('A6200-01', '분임조 등록카드', 'A-6200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-01.xlsx'),
  ('A6200-02', '분임조 활동계획서', 'A-6200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-02.xlsx'),
  ('A6200-03', '분임조 활동 회의록', 'A-6200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-03.xlsx'),
  ('A6200-04', '분임조 결과보고서', 'A-6200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/A6200-04.xlsx'),
  ('A6300-01', '품질문제 신고서', 'A-6300', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', NULL, NULL, 'templates/standard/A6300-01.xlsx'),
  ('A7100-01', '윤리경영행동지침', 'A-7100', '열람형(참조 문서) — 윤리경영 행동 지침(서약서): 지침 본문 10개조 기정의 + 서약(소속/서약자/서명) — 체결은 서면·서명 동선.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, NULL),
  ('A7100-02', '클린신고서', 'A-7100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '5', NULL, 'templates/standard/A7100-02.xlsx'),
  ('A8100-01', 'RISK 분석표', 'A-8100', '프로세스 리스크 분석표.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '6', NULL, 'templates/standard/A8100-01.xlsx'),
  ('A8101-01', '비상사태 발생시 대응 방안', 'A-8101', '열람형(참조 문서) — 비상사태 발생시 대응 방안: 674행 책자형 문서(목차·기본대응 절차·비상 연락체계·상황별 방안, 이미지 40장) 기정의. 기록 동선은 훈련결과 보고서(A8101-02)·평가표(A8101-03)로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, NULL),
  ('A8101-02', '비상사태 대비 훈련결과 보고서', 'A-8101', '좌/우 2벌 중 ★좌측(빈 틀)만 매핑 — 제목·목적·목표·훈련형태(체크 표기)·실시일자·주관팀·장소·동원장비·참석인원·참관감독·상황전파·시나리오·주요 훈련내용·참석자 명단. 우측 = E-7 팬더믹 작성례(모범 예시 성격 — 보존). 사진·상세 양식은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, 'templates/standard/A8101-02.xlsx'),
  ('A8101-03', '비상사태 대비 훈련 평가표', 'A-8101', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, 'templates/standard/A8101-03.xlsx'),
  ('A8101-04', '비상사태 검토 보고서', 'A-8101', '헤더 4(문서번호·작성일자·주관부서·작성자[자동]) + 참석자 grid(7~10행, 좌/우 2열 — 확인란 서명 몫) + 회의명·회의내용. 구분(비상계획검토) 기정의·사진 3장·결재는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6,8', NULL, 'templates/standard/A8101-04.xlsx'),
  ('B-2200', '지속적 개선업무 규정', 'B-2200', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, NULL),
  ('B1100-01', '부적합품 발생 통보서', 'B-1100', '공정/수입검사에서 부적합품 발생 시 작성. IATF §10.2 부적합 및 시정조치.', '["담당","팀장","사업부장"]', 'B2100-01', '이 부적합에 대한 시정조치를 요구합니다', NULL, '{
  "blocks": [
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "h1", "colSpan": 3 } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "h2" }, { "fieldKey": "h3" }, { "fieldKey": "h4" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "i1" }, { "fieldKey": "i2" }, { "fieldKey": "i3" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "i4" }, { "fieldKey": "i5" }, { "fieldKey": "i6" } ] },
    { "type": "section", "title": "부적합 내용" },
    { "type": "full", "fieldKey": "c1" },
    { "type": "full", "fieldKey": "c2" },
    { "type": "section", "title": "조사 내용" },
    { "type": "full", "fieldKey": "c3" },
    { "type": "section", "title": "조치 및 요구사항" },
    { "type": "grid", "columns": 1, "cells": [ { "fieldKey": "p1" }, { "fieldKey": "c4" }, { "fieldKey": "p3" } ] }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-01.xlsx'),
  ('B1100-02', '부적합품 발생 통보서 관리대장', 'B-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-02.xlsx'),
  ('B1100-03', '특채 의뢰서', 'B-1100', '부적합품에 대한 특별 채용(특채) 의뢰. 고객 승인 필요 여부 포함.', '["작성","검토","승인"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-03.xlsx'),
  ('B1100-04', '수리 작업 일지', 'B-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-04.xlsx'),
  ('B1100-05', '불량유출 봉쇄 작업표', 'B-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, '{
  "blocks": [
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a1" }, { "fieldKey": "a4" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a2" }, { "fieldKey": "a3" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "a5" }, { "fieldKey": "a6" }, { "fieldKey": "a7" } ] },
    { "type": "full", "fieldKey": "a8" },
    { "type": "section", "title": "불량유출 봉쇄 범위" },
    { "type": "full", "fieldKey": "b1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "b2" }, { "fieldKey": "c1" } ] },
    { "type": "section", "title": "봉쇄 방법 (분류·식별)" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "c2" }, { "fieldKey": "c3" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "c4" }, { "fieldKey": "c5" } ] }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-05.xlsx'),
  ('B1100-06', '폐기보고서', 'B-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-06.xlsx'),
  ('B1100-07', '품질문제 발생 신속 대응 계통도', 'B-1100', '열람형(참조 문서) — 품질문제 발생 신속 대응 계통도(도해 이미지) + 신속대응 조직 연락망. 작성 양식 아님 — 개정은 규정 개정 절차로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('B1100-08', '부적합품 처리 기준(가로)', 'B-1100', '열람형(참조 문서) — 부적합품 처리 기준 도해(전면 이미지 — 가로/세로 2시트 동일 문서). 작성 양식 아님. 처리 기록은 B1100-13 부적합품 처리대장으로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('B1100-09', '특채 관리대장', 'B-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-09.xlsx'),
  ('B1100-10', '폐기보고 관리대장', 'B-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-10.xlsx'),
  ('B1100-11', '부적합 보관장 관리 대장', 'B-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/B1100-11.xlsx'),
  ('B1100-12', '리크·리워크 이력대장', 'B-1100', '리크·리워크 이력대장(발생~리워크~재검사~판정 추적, 리워크 LOT 식별 -R).', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '2_9,6_10', 'templates/standard/B1100-12.xlsx'),
  ('B1100-13', '부적합품 처리대장', 'B-1100', '부적합(추정)품 처리대장(격리~재검사~폐기/리워크/복귀 수량 대사). 수량 대사(N열)는 자동판정 수식 보존.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '6_6', 'templates/standard/B1100-13.xlsx'),
  ('B2100-01', '시정/예방조치 요구서', 'B-2100', '부적합 사항에 대한 시정 또는 예방조치를 요구. IATF §10.2.3~10.2.6.', '["담당","팀장","사업부장","부사장","대표이사"]', 'B2100-03', '상세 개선 대책을 수립합니다', 'B1100-01', '{
  "blocks": [
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "s1" }, { "fieldKey": "s2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "s3" }, { "fieldKey": "s4" } ] },
    { "type": "grid", "columns": 1, "cells": [ { "fieldKey": "s5" } ] },
    { "type": "section", "title": "부적합 내용" },
    { "type": "full", "fieldKey": "s6" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "s7" }, { "fieldKey": "s8" } ] },
    { "type": "section", "title": "조치 내용 (수신처 작성)" },
    { "type": "full", "fieldKey": "s9" },
    { "type": "full", "fieldKey": "s10" }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-01.xlsx'),
  ('B2100-02', '시정 및 예방조치 등록대장', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-02.xlsx'),
  ('B2100-03', '개선 대책서', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, 'B2100-01', '{
  "blocks": [
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a1" }, { "fieldKey": "a2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "a3" }, { "fieldKey": "a4" } ] },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "a5" }, { "fieldKey": "a6" }, { "fieldKey": "a7" } ] },
    { "type": "section", "title": "문제 정의" },
    { "type": "full", "fieldKey": "p1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "p2" }, { "fieldKey": "p3" } ] },
    { "type": "full", "fieldKey": "p4" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "p5" }, { "fieldKey": "p6" } ] },
    { "type": "section", "title": "개선 대책 (8D)" },
    { "type": "full", "fieldKey": "d1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "d2" }, { "fieldKey": "d3" } ] },
    { "type": "section", "title": "개선 내용 및 유효성 확인" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "g1" }, { "fieldKey": "g2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "v1" }, { "fieldKey": "v3" } ] },
    { "type": "full", "fieldKey": "v2" }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-03.xlsx'),
  ('B2100-04', '장기테마', 'B-2100', '장기테마 개선 추진 일정 관리표(4행 블록 10건). 월별 진행상태 매트릭스·EXIT CRITERIA 는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-04.xlsx'),
  ('B2100-05', '즉실천항목', 'B-2100', '일일 품질(신속대응)회의 즉실천 항목 관리표(4행 블록 10건). 주차 라벨·즉실천 구분·진행상태 서브블록은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-05.xlsx'),
  ('B2100-06', '금형 진행사항 점검', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-06.xlsx'),
  ('B2100-07', '설비점검 진행사항', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-07.xlsx'),
  ('B2100-08', '4M변경 내역 및 적용일자 관리', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-08.xlsx'),
  ('B2100-09', '공정개선 T O 진행사항 점검', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-09.xlsx'),
  ('B2100-10', '용접 개선 T O 진행사항 점검', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-10.xlsx'),
  ('B2100-11', '고객사 불량 유효성 검증 관리대장', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-11.xlsx'),
  ('B2100-12', '유효성 점검 체크시트', 'B-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2100-12.xlsx'),
  ('B2200-05', '품질실적 월보', 'B-2200', '품질실적 월보(공정/고객/외주 PPM). PPM·목표달성 수식 보존.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', '6_7', 'templates/standard/B2200-05.xlsx'),
  ('B2300-01', '정성품질 CFT 업무 분장', 'B-2300', '열람형(참조 문서) — 정성품질 CFT 업무 분장표: 조직×역할(교육/점검·개선/유효성) 기정의. 작성 양식 아님 — 분장 개정은 지침 개정 절차로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, NULL),
  ('B2300-02', '정성품질 취합 대장', 'B-2300', '정성품질 점검 의견 취합 대장. 순번 열은 시트 프리셋.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-02.xlsx'),
  ('B2300-03', '정성품질 점검 체크시트', 'B-2300', '고객사 정성작업 유도방안 점검 체크시트(갑지). 최소 매핑 — 현황 블록 7필드. 점검 매트릭스(불량현황·항목별 점검)는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-03.xlsx'),
  ('B2300-04', '문제점 및 개선 제안서', 'B-2300', '문제점·개선 제안서. 분류 체크(□ 설비~기타)·사진/도식화는 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-04.xlsx'),
  ('B2300-05', '정성품질 개선 타당성 검토', 'B-2300', '개선 타당성 검토 회의록. 검토 문항 YES/NO 체크는 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-05.xlsx'),
  ('B2300-06', '유효성 평가 보고서', 'B-2300', '개선 유효성 평가 보고서. 합격/불합격 체크(□)·개선 추이도 그래프·개선 전후 사진은 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-06.xlsx'),
  ('B2300-07', '인라인 공정불량 사례 시트', 'B-2300', '관리부실 공정불량 사례.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-07.xlsx'),
  ('B2300-08', '정성품질 순회 점검 시트', 'B-2300', '정성품질 순회 점검 시트 — 점검 항목 16(작업환경~재발방지) 시트 프리셋, 라인별 점검결과 grid. 점검일/점검자는 시트 수기.', '["담당","사업부장","대표이사"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '10', NULL, 'templates/standard/B2300-08.xlsx'),
  ('D-1100', '제품 특성 안전관리 규정', 'D-1100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, NULL),
  ('D-2100', '안전보건관리규정', 'D-2100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('D-2101', '작업장 안전관리 지침', 'D-2101', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('D1100-01', '안전 사고 발생보고서', 'D-1100', '사고 헤더 8(사고일시·소속·상해부위·성명·사고장소·입사일자·작업명·목격자) + 발생경위(6하원칙)·원인분석·조치사항(팀장 기재) textarea 3. 결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-01.xlsx'),
  ('D1100-02', '연간 제품안전교육 계획서', 'D-1100', '제목(연도)·작성일·작성부서·연도 표기 + 월별 계획/실적 각 12칸(3열 병합 개별 매핑) + 특기사항. 범례(○◐●)·교육 대상 각주 기정의·결재 6단 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-02.xlsx'),
  ('D1100-03', '제품 안전교육 보고서', 'D-1100', '훈련 헤더 5(훈련일자·주관부서·참석인원·참석대상·훈련구분) + 목적·내용·훈련결과(효과성)·참석자 대형 textarea 4. 결재 3단 서명 몫. 제품 안전(PSCR) 교육 증빙 — 심사 갭 이력 연계.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-03.xlsx'),
  ('D1100-04', '공정 안전점검 연간 계획_실적', 'D-1100', '제목(사업부)·연도 + 5행 grid(계획·실적·지적 건수·개선 완료·유효성 점검 — 행 라벨 기정의 × 월 12 + 비고). 절차 안내(11행~) 기정의·결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-04.xlsx'),
  ('D1100-05', '공정 안전점검 체크시트', 'D-1100', '제목(사업부)·점검일·점검자 + 점검 grid(5~34행 30행 — 구분·점검항목 기정의[가스/전기 시설물 등], 점검 결과·유효성점검만 기입) + 특기사항. 결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-05.xlsx'),
  ('D1100-06', '공정 안전점검 개선대책', 'D-1100', '제목(사업부)·개선부서·개선담당(정/부) + 지적사항·개선방안 + 점검일자·개선완료일. 개선 전/후 사진(6~20행)은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '4,8', NULL, 'templates/standard/D1100-06.xlsx'),
  ('E-1100', '환경 리스크 평가 규정', 'E-1100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6', NULL, NULL),
  ('E-1101', '환경측면 파악 및 리스크 평가표 작성지침', 'E-1101', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '6', NULL, NULL),
  ('E-2100', '안전보건,환경 법규관리 규정', 'E-2100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, NULL),
  ('E-3100', '환경운영관리 규정', 'E-3100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3101', '작업환경관리 지침', 'E-3101', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3102', '소음진동 관리 지침', 'E-3102', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3103', '폐기물 관리 지침', 'E-3103', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3104', '유해화학물질 관리 지침', 'E-3104', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3105', '대기관리 지침', 'E-3105', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3106', '수질관리 지침', 'E-3106', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3107', '소방시설 관리 지침', 'E-3107', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-3108', '에너지 관리 지침', 'E-3108', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '8', NULL, NULL),
  ('E-5100', '감시 및 측정관리 규정', 'E-5100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '9', NULL, NULL),
  ('F1100-01', '연간 사내외 교육훈련 계획서', 'F-1100', '연간 교육훈련 계획 대장(월별 일정 12열).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-01.xlsx'),
  ('F1100-02', '교육 이수 보고서', 'F-1100', '작성일자 + 이수 헤더 9(과정명·소속/직위·성명·교육장소·교육기관·교육비·교육기간·이수시간·교육구분) + 교육명·교육 목적 + 교육결과 체크 2(적용성·도입 여부 — 해당 칸 ■ 표기) + 전달교육(실시일자·대상). 보고서 확인란 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-02.xlsx'),
  ('F1100-04', '지식 관리표', 'F-1100', '조직 지식 관리표(프로세스별 지식 목록). 연번(B열)은 원본 수식이 기록행 소속이라 클리어 — 수기 기입.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-04.xlsx'),
  ('F1100-05', '사내교육 관리대장', 'F-1100', '교육 grid(8~24행 17행: 교육일자·교육명·관리자·작업자). 순번 자동 수식(A열) 보존·결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-05.xlsx'),
  ('F1100-06', '사내 교육 보고서', 'F-1100', '작성일자·작성자(표기) + 교육 헤더 7(교육명·구분[■사내/□사외 표기]·교육강사·교육일자·교육장소·교육대상·교육인원) + 교육내용. 교육 사진(워터마크 필수)·교육 자료 첨부 영역은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1100-06.xlsx'),
  ('F1101-01', '신임 교육 계획서', 'F-1101', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1101-01.xlsx'),
  ('F1101-02', '신임 교육 일지', 'F-1101', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F1101-02.xlsx'),
  ('F1101-03', '신규입사자 온보딩 체크리스트(오퍼레이터)', 'F-1101', '오퍼레이터 온보딩 체크리스트.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '관리팀', '7.2', NULL, 'templates/standard/F1101-03.xlsx'),
  ('F1101-04', '신규입사자 온보딩 체크리스트(관리자)', 'F-1101', '관리자 온보딩 체크리스트.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '관리팀', '7.2', NULL, 'templates/standard/F1101-04.xlsx'),
  ('F2100-01', '사내 자격 관리대장', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-01.xlsx'),
  ('F2100-02', '사내 자격 인증 카드', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-02.xlsx'),
  ('F2100-03', '사내 자격 인증서', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-03.xlsx'),
  ('F2100-04', '자격인증 변경 요청서', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-04.xlsx'),
  ('F2100-05', '공정면허 이론평가서', 'F-2100', '공정면허 이론평가서 묶음(1안·2안) — 실제 작성은 F2100-05-01 / F2100-05-02.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-05.xlsx'),
  ('F2100-05-01', '공정면허 이론평가서 1안', 'F-2100', '공정면허 이론 평가서(갑지+을지, 10문항 프리셋). 최소 매핑 — 응시 정보·점수만. 문항별 답안 기입·자격구분 체크(□)는 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-05-01.xlsx'),
  ('F2100-05-02', '공정면허 이론평가서 2안', 'F-2100', '자격인증 이론평가 2안(10문항+정답란 프리셋). 최소 매핑 — 응시 정보만. 문항별 답안 기입은 시트 수기(정답열 AF는 채점용 프리셋).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-05-02.xlsx'),
  ('F2100-06', '공정면허 실기평가서', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-06.xlsx'),
  ('F2100-07', '숙련도_다기능 평가 계획', 'F-2100', '연도(제목 병합) + 평가 계획 grid(6~9행 4항목: 평가항목·주기·1~12월[계획○/실적● 병기 칸]·달성율). 범례·점수 등급·평가기준 각주 기정의. 결재 3단 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-07.xlsx'),
  ('F2100-08', '숙련도 평가표', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-08.xlsx'),
  ('F2100-09', '작업자 현장 직무 현황', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-09.xlsx'),
  ('F2100-10', '작업자 숙련도 CHECK SHEET', 'F-2100', '매트릭스 채점형. 대상자·특이사항·작성자만 앱 기입.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-10.xlsx'),
  ('F2100-11', '자격 인증 교육 및 평가서', 'F-2100', '인적 정보 9(성명·사업부·직책·학력·전공·입사일자·현직무·교육명·교육기간) + 교육과정 grid(12~14행: 과정명·기간, 교육처/강사는 통합 1칸) + 시간표 grid(2행 병합 4블록×3열) + 평가 점수(이론 Y26·실기 Y31 — 소계 Y36 수식은 시트 몫) + 교육자료. 근무경력(Y7 DATEDIF)·경력 기준일·인증 기준·결재(팀장/사장)는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-11.xlsx'),
  ('F2100-12', '공정별 전담자 및 대체자 관리기준', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-12.xlsx'),
  ('F2100-13', '공정면허 자격인증 평가서(종합)', 'F-2100', '사내 자격인증 평가 명부 grid(6~14행 9명: 소속·성명·계수형 R&R·계량형 R&R·실기·이론·근무년수·판정 LEVEL·비고) + 작성자(결재 담당 AJ2). 합계(AG SUM 수식)·평가 주기/방법 각주는 시트 몫. 평가자=품질보증팀장(각주 기정의).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-13.xlsx'),
  ('F2100-14', '공정면허 자격인증평가(갑지)', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-14.xlsx'),
  ('F2100-15', '공정 자격인증카드_공정 게시용', 'F-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '총무팀', '7', NULL, 'templates/standard/F2100-15.xlsx'),
  ('H-1100', '계약검토 규정', 'H-1100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, NULL),
  ('H1100-01', '제조타당서 검토서', 'H-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-01.xlsx'),
  ('H1100-02', '개발의뢰 접수대장', 'H-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-02.xlsx'),
  ('H1100-03', '원가계산서', 'H-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-03.xlsx'),
  ('H1100-04', '원단위 원가분석', 'H-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/H1100-04.xlsx'),
  ('H2100-02', '월 납품량 분석 보고서', 'H-2100', '월 납품량 분석 보고서. 최소 매핑 2(목표금액·작성자) — 일자별 수주/출고/납입율 매트릭스(수식 다수)·표제 (00월)은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, 'templates/standard/H2100-02.xlsx'),
  ('H2100-03', '일일 납품 실적 보고서(', 'H-2100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, 'templates/standard/H2100-03.xlsx'),
  ('H3100-01', '연간 고객만족도 모니터링', 'H-3100', '지표 10종·주기·단위·주관부서 = 시트 기정의(블록당 10행 고정 — 1~10행=고객사1·11~20=고객사2·21~30=고객사3), 년누적(S열 SUM/AVERAGE 수식)은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-01.xlsx'),
  ('H3100-02', '고객만족도 조사 시행 계획서', 'H-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-02.xlsx'),
  ('H3100-03', '고객만족도 평가서(설문지)', 'H-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-03.xlsx'),
  ('H3100-04', '종업원 만족도 조사 설문지', 'H-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-04.xlsx'),
  ('H3100-05', '종업원 만족도 조사결과 보고서', 'H-3100', '배포/회수(라벨 내장 셀)·집계 매트릭스는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-05.xlsx'),
  ('H3100-06', '종업원 동기부여 계획서', 'H-3100', '종업원 동기부여 계획서. 항목(지원금·사내행사·복지시설·작업환경개선)은 시트 프리셋.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-06.xlsx'),
  ('H3100-07', '종업원 동기부여 실적평가서', 'H-3100', '종업원 동기부여 실적평가서. H3100-06 동형(추진결과/조치계획 열).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '9', NULL, 'templates/standard/H3100-07.xlsx'),
  ('H3200-01', '고객불만 접수 대응 현황 보고서', 'H-3200', '고객 불만 접수~대응~결론 현황 대장(2행 블록 18건 — 본행 + 불량수량/기타경비 상세행). 대응시간·PPM·경비 합산은 시트 수식 보존. 표제 년/월은 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/H3200-01.xlsx'),
  ('H3200-02', '고객불만 대응 조치 결과 보고서', 'H-3200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, '{
  "blocks": [
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "a1" }, { "fieldKey": "a2" }, { "fieldKey": "a3" } ] },
    { "type": "section", "title": "1. 고객불만 접수 이력" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "r1" }, { "fieldKey": "r2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "r3" }, { "fieldKey": "r4" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "r5" }, { "fieldKey": "r6" } ] },
    { "type": "section", "title": "2. 고객불만 내용" },
    { "type": "full", "fieldKey": "m1" },
    { "type": "section", "title": "3. 고객불만 대응 결과" },
    { "type": "grid", "columns": 3, "cells": [ { "fieldKey": "g1" }, { "fieldKey": "g2" }, { "fieldKey": "g3" } ] },
    { "type": "full", "fieldKey": "g4" },
    { "type": "section", "title": "4. 고객불만 대응 조사 결과" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "i1" }, { "fieldKey": "i2" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "i3" }, { "fieldKey": "i4" } ] },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "i5" }, { "fieldKey": "i6" } ] },
    { "type": "section", "title": "5. 협의 · 최종 결론" },
    { "type": "full", "fieldKey": "c1" },
    { "type": "grid", "columns": 2, "cells": [ { "fieldKey": "c2" } ] },
    { "type": "full", "fieldKey": "c3" }
  ]
}', '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/H3200-02.xlsx'),
  ('J-1100', '개발업무 규정', 'J-1100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, NULL),
  ('J-1101', '공정FMEA 작성 및 관리 지침', 'J-1101', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '6,8', NULL, NULL),
  ('J-2100', '양산부품 승인업무 규정', 'J-2100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('J-3100', '4M 변경관리 규정', 'J-3100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, NULL),
  ('J-4100', '도면관리 규정', 'J-4100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, NULL),
  ('J-4200', '도면 부품 일치성 점검 지침', 'J-4200', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, NULL),
  ('J1100-01', '개발일정 계획서', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-01.xlsx'),
  ('J1100-02', '공정흐름도', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-02.xlsx'),
  ('J1100-03', '특별특성 목록표', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-03.xlsx'),
  ('J1100-04', '부품개발 요청서', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-04.xlsx'),
  ('J1100-05', '제품 품질계획요약 및 완료확인서', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-05.xlsx'),
  ('J1100-06', '개발품 TRY-OUT 일정 계획서', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-06.xlsx'),
  ('J1100-07', '개발품 TRY-OUT 완료 보고서', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-07.xlsx'),
  ('J1100-08', '납입용기 설정서', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-08.xlsx'),
  ('J1100-09', '제조타당성 확인서', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-09.xlsx'),
  ('J1100-10', '제품 법_규제 요구사항 목록표', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-10.xlsx'),
  ('J1100-11', 'PM 및 MDT 선정기준', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-11.xlsx'),
  ('J1100-12', '에스켈레이션 기준', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-12.xlsx'),
  ('J1100-13', '양산이관기준', 'J-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-13.xlsx'),
  ('J1100-14', '고객 접수 도면 검토서', 'J-1100', '5페이지 도면 검토서. 치수 검토표(4·5면)·도면 첨부는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J1100-14.xlsx'),
  ('J1101-01', '공정 FMEA 4판 SHEET', 'J-1101', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '6,8', NULL, 'templates/standard/J1101-01.xlsx'),
  ('J1102-01', '관리계획서 1판 표지 ( 갑)', 'J-1102', 'Control Plan 갑지 표지 — 업체명·차종·부품명/품명·부번/품번·상호기능팀원·업체코드·제정일자 + 개정 1행(개정일자·개정사유·작성·검토·승인). 단계 체크(시작/양산)·고객 승인 3(서명 동선)·공정도/LAYOUT(12행~)은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J1102-01.xlsx'),
  ('J1102-02', '관리계획서 특별특성', 'J-1102', '특별특성 목록(AIAG 서식 — 번호·근거·시방/공차·분류·공정/제품). 상단 승인 블록은 병합 구조 부재로 시트 수기, 삽화 열은 이미지라 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J1102-02.xlsx'),
  ('J1102-03', '관리계획서 체크리스트', 'J-1102', 'AIAG 관리계획서 체크리스트 21문항(예/아니오/N.A + 코멘트·책임자·기한, 행 순서 = 문항 1~21). 단계 체크(시작품~양산)는 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J1102-03.xlsx'),
  ('J1103-01', '작업표준서', 'J-1103', '작업표준서 — 헤더 6(품번·품명·차종·공정명·설비명·작성일) + 조건 관리 grid + 자주검사 grid + 서술 4(작업순서·안전·부적합 및 이상조치 절차·중요 부적합 유형) + 금형·공구 grid + 개정이력 grid. 도식화 2면·결재 4단은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/J1103-01.xlsx'),
  ('J3100-01', '4M 변경 의뢰서', 'J-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-01.xlsx'),
  ('J3100-02', '사양변경접수대장', 'J-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-02.xlsx'),
  ('J3100-03', '4M 변경 관리대장', 'J-3100', '4M 변경 관리대장(신양식) grid(6~17행 12행 × 25열 — 변경 신고 내용 10·표준 문서류 개정 4·승인 처리 3조·적용 시점 2·초도검증 4·판정·비고). 결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-03.xlsx'),
  ('J3100-04', '4M변경 판단기준', 'J-3100', '열람형(참조 문서) — 4M 변경 판단기준표: 구분(사람·설비·재료·방법)×세부내용×처리구분(●) 전 칸 기정의 기준 문서. 작성 양식 아님 — 판단 기록은 J3100-01 의뢰서·J3100-08 마스터리스트로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, NULL),
  ('J3100-05', '변경점 관리 계획 대비 실적', 'J-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-05.xlsx'),
  ('J3100-06', '변경점 점검 조직도', 'J-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-06.xlsx'),
  ('J3100-07', '4M 변경점 관리 점검 C SHEET', 'J-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', NULL, 'templates/standard/J3100-07.xlsx'),
  ('J3100-08', '4M 변경 마스터리스트', 'J-3100', '4M·설계변경 마스터리스트.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '7,8', '6_2', 'templates/standard/J3100-08.xlsx'),
  ('J4100-01', '도면관리대장', 'J-4100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '개발팀', '8', NULL, 'templates/standard/J4100-01.xlsx'),
  ('J4200-01', '도면 일치성 점검 체크시트', 'J-4200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/J4200-01.xlsx'),
  ('K1100-01', '원자재 입고 요청서', 'K-1100', 'PURCHASE ORDER 원자재 입고 요청서. 당사 정보(상호~담당자)는 시트 프리셋.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1100-01.xlsx'),
  ('K1100-02', '원소재 생산 의뢰서', 'K-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1100-02.xlsx'),
  ('K1100-07', '기본공급 계약서', 'K-1100', '열람형(참조 문서) — 기본공급 계약서: 조문 전문(제1장~ 기본 합의·개별 약정·납품 등) 기정의 법률 문서. 체결은 서면·인감 동선.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K1100-08', '클레임 보상협정서', 'K-1100', '열람형(참조 문서) — 클레임 보상협정서: CLAIM 정의·보상책임·인정 조문 전문 기정의 법률 문서. 체결은 서면·인감 동선.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K1100-09', '품질 보증 협정서', 'K-1100', '열람형(참조 문서) — 품질 보증 협정서: 품질 보증 업무·실시사항·사양 확인 조문 전문 기정의 법률 문서. 체결은 서면·인감 동선.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K1100-10', '원재료 법_규제 요구사항 목록표', 'K-1100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1100-10.xlsx'),
  ('K1200-01', '①협력업체 등록대장', 'K-1200', '업체 2행 블록 grid 10개(상단행: 등록일자·업체명·사업자번호·주소·연락책임자·생산/거래품목·인증 4[IATF/9001/14001/45001 — 유효기간 기록 칸] / 하단행: 대표자·업종/업태·연락처 2).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-01.xlsx'),
  ('K1200-02', '②승인 자재 목록 (AVL. AML)', 'K-1200', '작성일자·작성자 + 자재 grid(7~24행 18행: 분류·업체명·공급 제품명·품번·품질/납기 리스크·QMS 인증·정기 평가 3개년·실적 품질/납기 3개년). 결재 3단 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-02.xlsx'),
  ('K1200-03', '③협력업체 사후 평가 계획서', 'K-1200', '제목(연도) + 업체 계획 grid(계획행 13블록: 업체명·등급·평가주기·1~12월 일정·비고) + 실적 grid(실적행: 1~12월) + 작성자(결재 작성 O2). 업체 블록 = 2행(계획/실적) 병합·순번 A열 자동 수식, 월 헤더(G5~R5) 연쇄 수식·검토/승인 결재는 시트 몫. 범례: 일정 칸에 ○ 계획 ● 실적 관례.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-03.xlsx'),
  ('K1200-04', '④업체 실태 조사서', 'K-1200', '갑지 매핑 — 회사 정보 10(회사명·사업자번호·대표자·업종/업태·소재지 3·설립일자·기업형태 3칸 체크·자본금) + 거래처 grid(11~16행) + 면적 2·종업원 4 + 기업특색 3(경영방침·품질방침·전문기술력) + 기타사항·조사결과. 을지(32행~ 첨부 자료)·조사자 3(인)은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-04.xlsx'),
  ('K1200-04-01', '타사업부 실적,체제 평가 계획서', 'K-1200', '타 사업부 실적·체제 평가표(납기20·품질30·환경10·공정/품질리스크40 배점, 평가등급 A/B/C). 평가 항목·배점·기준은 시트 프리셋. 검토/승인 결재는 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-04-01.xlsx'),
  ('K1200-05', '⑤협력업체 체제 평가표', 'K-1200', '평가업체명·평가일자 + 평가자 grid(7~10행: 소속·직위·성명 — 서명란 몫) + 득점 grid(13~31행 19행: 품질 9·기술 4·회사관리 4·납기 2 — 항목·기준·배점·평가부서 기정의, 득점만 기입) + 부서별 평가의견 3(품질보증·개발·구매). 결재 3단 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-05.xlsx'),
  ('K1200-06', '협력사 월별 모니터링', 'K-1200', '연도 표기·업체명 3. 지표 8종 × 월 12열 실적값·년누적/달성율 수식은 시트 몫(수식 보존).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-06.xlsx'),
  ('K1200-07', '외주 ISIR·검사협정 접수대장', 'K-1200', '외주업체(가공·프레스·표면처리) ISIR/검사협정 접수·개정 이력 대장 — 심사원 단골 질문 대비.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K1200-07.xlsx'),
  ('K2100-01', '장기재고관리 현황', 'K-2100', '장기재고 현황 대장(강종·재질·규격·수량·용도·관리방안·상태).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-01.xlsx'),
  ('K2100-04', '재고조사표', 'K-2100', '작성기준일·부서명·작성자 + 재고 실사 grid(7~33행 27행: 구분·강종·제품규격 O.D/T/길이·재고·중량·단가·금액·보관장소) + 실사중량. 합계(34행 SUM 3식)는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-04.xlsx'),
  ('K2100-05', '장기 재고 점검대장', 'K-2100', '장기재고 품질 열화 Check Sheet. 평가 정보(평가일자·평가팀·평가자) + 점검 대상(품명/품번 4열) + 점검 점수 grid(10항목×4품목, 2행 병합 블록) + 전월점수 4 + 하단 점검 grid(품번·재고일치·식별상태·유해결함 4행) + 조치(시정조치일·재평가일·재평가자·의견). 열별 소계(28행 SUM)·배점 기준표는 시트 몫, 판정(□합격/□시정조치)은 앱 기록·시트 체크 수기, 승인란 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-05.xlsx'),
  ('K2100-06', '선입선출 관리 기준서', 'K-2100', '선입선출 관리 기준서. 상단 개요 블록(A4:AV14)·도해 그림은 시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-06.xlsx'),
  ('K2100-07', '장기 재고 관리 기준서', 'K-2100', '열람형(참조 문서) — 장기 재고 관리 기준(목적·정의·3개월 선정 기준) 본문 + 기준표 기정의. 작성 양식 아님(현황 기록은 K2100-01 장기재고관리 현황으로).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, NULL),
  ('K2100-08', '소모품 월소요량 및 안전재고', 'K-2100', '월 4행 블록 12개(1~12월) — 생산수량(4행 병합)·소모품 소요 기재(4행 병합)·월말 실사재고 4종(알곤/질소/와이어/용접팁 — 유형 라벨 시트 기정의)·판정(4행 병합). stride 4 grid 4개(블록 내 행 오프셋 = 재고 4종). 소계(I55 SUM 수식)·월 라벨·결재(담당/팀장)는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-08.xlsx'),
  ('K2100-09', '소모품 사양 및 공급처 지정 현황', 'K-2100', '소모품 grid(5~8행 4행: 구분·사양·공급사 및 연락처·공급 소요일·비고). 소모품 사진 열·변경 절차 각주 기정의·결재는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', NULL, 'templates/standard/K2100-09.xlsx'),
  ('K2100-10', '자재 보관장 점검표·Lay-Out', 'K-2100', '월간점검 시트 대장형.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '구매팀', '8', '5_2', 'templates/standard/K2100-10.xlsx'),
  ('L-4100', '통계적 기법적용 규정', 'L-4100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, NULL),
  ('L-4101-01', 'SPC 평가표', 'L-4101', 'SPC 평가표(Xbar-R·Cpk 계산기). 측정 데이터 매트릭스·통계치/판정은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L-4101-01.xlsx'),
  ('L1100-01', '설비제작 사양서', 'L-1100', '문서형 대작(226행 사양서) — 식별 헤더 3(품명·차종·목적)만, 상세 본문은 사람 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-01.xlsx'),
  ('L1100-02', '설비제작 진행 체크리스트', 'L-1100', '계약 헤더 8(계약명·제작기간·제조사·대표자·연락처·발주처·담당자·주소). 본문 = "장비제작업체 제작진행 리스트 첨부할것" 기정의 — 진행 리스트는 첨부 동선(시트 몫).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-02.xlsx'),
  ('L1100-03', '입회검수 체크시트', 'L-1100', '지적사항 grid(5~30행 26행: 지적사항·대책·개선완료일·비고). NO는 수기·결재 4단 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-03.xlsx'),
  ('L1100-04', '설비 TRY-OUT 결과 보고서', 'L-1100', '헤더 6(장비명·제작처·설치장소·일시·작성자[자동]·작업자) + 문제점/조치 grid(6~17행 12행: 문제점 및 현상·조치내용·일정·비고/결과).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-04.xlsx'),
  ('L1100-05', '납품 및 시운전(검수) 확인서', 'L-1100', '공급자 정보 5(상호·사업자등록번호·대표 성명·전화번호·소재지) + 품목 grid(2행 병합 2블록: 공급일자·품목·규격·수량·금액). 계 V.A.T미포함(H17=H15+H13 수식)·사진 영역·하단 확인 블록은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-05.xlsx'),
  ('L1100-06', '설비고장 조치 보고서', 'L-1100', '헤더 8(설비명·해당사업부·설비번호·부품명·발생일·조치자·조치일·조치업체·D/T) + 현상 3(무엇이/어떻게/결과는) + 조치내용 + 원인(왜-왜) + 재발방지대책 3조(설비면/관리면/유사설비 수평전개 × 내용·누가·언제·완료유무). 현상도/스케치는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-06.xlsx'),
  ('L1100-07', '설비 일상 점검표', 'L-1100', '헤더(설비명·설비번호·년월) + 점검항목 grid(2행 병합 4블록: 점검항목·판단기준). 점검방법(육안 기정의)·일별 결과 31열(N~AR)은 현장 수기 = 시트 몫·범례/점검시간/확인란 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-07.xlsx'),
  ('L1100-08', '설비 리스트', 'L-1100', '제목(사업부 기입)·작성 부서 + 설비 grid(4~22행 19행: 공정·설비번호·설비명·구입가격·제작/구입일자·제조사·전기용량·설비개조이력·비고). NO는 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-08.xlsx'),
  ('L1100-09', '설비 이력카드', 'L-1100', '설비 카드 + 수리/보전 이력 대장.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-09.xlsx'),
  ('L1100-10', '제조설비 관리대장(갑지)', 'L-1100', '갑지(리스트) 매핑 — 제목(사업부)·작성 부서 + 설비 grid(4~22행 19행, L1100-08 동형·열 좌표 상이). 을지(설비별 카드)는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-10.xlsx'),
  ('L1100-11', '년간 예방보전 계획서', 'L-1100', '제목(연도)·범례/작성일자 + 설비 3행 병합 10블록(6:8~33:35) — 계획(○)행 grid(설비명·설비번호·점검주기·1~12월·비고) + 실시(●)행 grid(1~12월, stride 3). NO·정/일 구분 라벨은 시트 기정의.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-11.xlsx'),
  ('L1100-12', '월간설비 정기 점검 계획서', 'L-1100', '제목(월 기입)·작성 부서 + 점검항목 grid(5행 병합 4블록: 점검항목·점검방법·판단기준·이상발생 및 조치사항·비고 — 블록 대표 1행 매핑, 상세 다행 기재는 시트 보완). 참고사진(C열 이미지)·결재 4단은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-12.xlsx'),
  ('L1100-13', '테마별 설비 정기점검 계획서(갑지)', 'L-1100', '갑지(연간 계획) 매핑 — 제목(연도)·작성 부서·작성일자 + 월별 중점 점검 테마 12칸 + 주차별 점검 grid(1~5주차: 부서·내역/테마/테마별 내역) + 비고. 을지(월별 중점점검 실기록 블록 누적)는 시트 몫. 결재 5단 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-13.xlsx'),
  ('L1100-14', '중요설비 체크리스트', 'L-1100', '작성 부서 + 설비 평가 grid(19~30행 12행: 설비번호·장비명·평가항목 1~10·판정·비고). 상단 평가기준표·범례(A~D등급)·부서 열(세로 병합 기정의)·합계(AB SUM 수식)는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-14.xlsx'),
  ('L1100-15', '업무 일지', 'L-1100', '업무일지. 보강 = 영선활동·명일 예정업무 grid(각 4블록) + 일자 매핑. 연속 페이지(50행~)·결재 5단은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-15.xlsx'),
  ('L1100-16', '스페어파트 관리대장', 'L-1100', '제목(년월) + SPARE PARTS 대장 grid(4~23행 20행: 부품명·규격·적정재고·현재재고 1~4주·메이커·구매처·구입 소요시간·보관위치·비고) + 구매 업체 연락처 2행 블록 grid 10개.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-16.xlsx'),
  ('L1100-17', '고정자산 폐기 품의서', 'L-1100', '작성일자·작성자 + 폐기 자산 grid(6~9행 4행: 입고일자·제조회사·자산명·형식·설비번호·단위·수량·처리방법·잔존가·비고) + 사유·첨부·폐기내용 + 하단 설비 식별 3(설비명·설비번호·부서/공정명). 폐기 설비 사진(23~37행)·결재 2벌(폐기부서/결재)은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-17.xlsx'),
  ('L1100-18', '풀프로프 설비 점검 일지', 'L-1100', '2부 — ①F/P 설비 현황 리스트 grid(5~19행 15행: 라인명·설비번호·설비명·측정항목·비고 — 점검주기 월1회 병합 기정의) ②하단 점검일지(년월 + 설비명 + 점검항목 2행 블록 5개[기준/방법 기정의]: 작동여부·비고). 하단 사업부/라인명 라벨은 값칸 불명(라벨 연속 배치) — 시트 수기. 결재 4단 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-18.xlsx'),
  ('L1100-19', '설비 이관 교육결과 보고서', 'L-1100', '전달 교육 보고서 — 헤더 8(소속·직위·작성자[자동]·교육장소·교육일자·강사명·교육목적·교육명) + 참석자 grid(9~12행, 좌/우 2열 — 소속·직위·성명) + 교육내용 textarea. 교육 사진(27행~)·결재 4단은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-19.xlsx'),
  ('L1100-20', 'F_P 이상발생 점검 체크시트', 'L-1100', '제목(월) + 점검일 2(좌/우 회차) + 점검 grid(29~33행 5항목[전압·전류·유량·Tip·원점 기정의]: 좌/우 조건 변경 값·작동상태). 기준값 표(16~20)·점검 순서 안내·기록방법(○/×) 기정의, 하단 2차 표(36~41행 회차 연장)·비고 영역·결재는 시트 몫. 주 1회(금) 작성.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-20.xlsx'),
  ('L1100-21', '설비 데이터 빽업 기준서', 'L-1100', '설비별 빽업 내역 grid(23~34행 12행, 좌/우 2열 통합 — 구분·설비명·빽업 항목 ×2). 설비 LAY-OUT 이미지(4~20행)·빽업 기준 4개조(35~39행 기정의)는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-21.xlsx'),
  ('L1100-22', '설비 데이터 빽업 관리대장', 'L-1100', '반기 1면 — 행렬 전치형(설비 A-1~A-11 열 × 일자/빽업자/차기 행)이라 grid 불가 → 개별 매핑: 제목(연도) + 상단 6열(빽업 일자·빽업자·차기 계획) + 하단 5열(빽업 일자·빽업자) + 특이사항 2. 설비 라벨(A-1~A-11) 기정의·결재는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-22.xlsx'),
  ('L1100-23', '설비관리 기준서', 'L-1100', '설비 식별 3(설비명·설비등급·설비업체) + 점검항목 grid(5~23행 2행 병합 10블록: 점검항목·규격·점검방법) + 재개정 이력 grid(26~29행: 개정일자·개정 사유·작성·검토·승인). 주기/담당자/기록 열(5블록 대형 병합 기정의)·설비 도식화·범례·상단 결재는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-23.xlsx'),
  ('L1100-24', '설비능력 지수표', 'L-1100', '헤더 입력 10을 원 입력 셀(B7~B10·B13~B18·C17)로 매핑 — 종전 J8/M8 등은 미러 수식 셀이라 수식 파괴 충돌. 측정값·수식은 시트 보호.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', NULL, 'templates/standard/L1100-24.xlsx'),
  ('L1100-25', '금형 점검 체크시트(일상/정기/보관)', 'L-1100', NULL, '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '7,8', '4_1,4_2,4_3,4_4,4_5', 'templates/standard/L1100-25.xlsx'),
  ('L1200-01', '치공구 관리대장', 'L-1200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-01.xlsx'),
  ('L1200-02', '치공구 이력카드', 'L-1200', '금형·치공구 카드 헤더 7(MODEL·공정명·사용장비·규격·재질·제작처·금형구분) + 사용장비 목록 grid(6~8행: 생산업체·이관일·비고) + 파손·변경 이력 grid(12~27행 16행: 날짜·이력·수량). 금형 약도는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-02.xlsx'),
  ('L1200-03', '지그 관리대장', 'L-1200', '작성일·작성 부서·작성자 + 지그 2행 블록 grid 9개 — 상단행(자산관리번호·차종·ASSY 부품번호·EO/NO·치형구 종류·공정명·규격·사용기계·대여/공증일·비고) + 하단행(단품 부품번호·부품명·재질·현 보유장소·중량·제작처). 순번은 시트 기정의.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-03.xlsx'),
  ('L1200-04', '지그 이력카드', 'L-1200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-04.xlsx'),
  ('L1200-05', '지그 및 치공구 검사 성적서', 'L-1200', '헤더 9(품명·적용공정명·규격·제작처·측정의뢰일·측정의뢰자·관리번호·측정일·측정자) + 검사 grid(22~32행 11행: 검사항목·검사기준·측정치·판정) + 비고. 개략도(도면 대체 문구 기정의)·결재 4단은 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-05.xlsx'),
  ('L1200-06', 'CF 점검기준서', 'L-1200', '점검 grid(5~8행 4행: 항목·규격·확인방법·주기) + 비고·제정일자 + 개정란 grid(11~14행: 개정일자·개정사유·작성·검토·승인). C/F 사진(점검 POINT 표기)·결재는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-06.xlsx'),
  ('L1200-07', 'CF 점검 시트', 'L-1200', 'C/F(체크 픽스처) 분기 점검(연 4회, 행 순서 = 1~4분기). 점검 기준행·분기 라벨은 시트 프리셋. 점검 담당 = 품질보증팀.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-07.xlsx'),
  ('L1200-08', '지그계약서', 'L-1200', '열람형(참조 문서) — 검사구·물품납입 계약서 조문 전문(제1~n조·계약금액·지불조건·지체상금, 갑을 인적사항·인감 날인).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, NULL),
  ('L1200-09', '지그 사용대차 계약서', 'L-1200', '열람형(참조 문서) — 지그 사용대차 계약서 조문 전문(Ⅰ장 총칙~관리의무, 자산보호·소유권 확인 목적). 작성 양식 아님: 동일 사유. 대여자산 기록은 L1200-10 대여자산 관리대장으로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, NULL),
  ('L1200-10', '대여자산 관리대장', 'L-1200', '협력회사 대여자산(설비·금형·치공구) 관리대장. Set 단위 작성. 활용여부 관리기호(A양산/B A/S용/C불용)는 시트 상단 프리셋.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-10.xlsx'),
  ('L1200-11', '지그 및 금형 보관 위치 식별표', 'L-1200', '제목(구역 기입) + 보관 슬롯 6개(3열×2단) × 위치번호/관리번호/품명 = 18칸. 관리기준 본문(4개조)·지그 보관대 표기·결재는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', NULL, 'templates/standard/L1200-11.xlsx'),
  ('L1200-12', '지그·치공구 점검 체크시트', 'L-1200', NULL, '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산기술팀', '8', '3_3,3_7', 'templates/standard/L1200-12.xlsx'),
  ('L2100-01', '수입검사표준', 'L-2100', '수입검사표준 — 품번별 검사 기준·항목 작성 → 엑셀 출력.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2100-01.xlsx'),
  ('L2100-05', '공정 순회검사(패트롤) 시트', 'L-2100', '공정 순회검사(패트롤) 시트 — 순회검사 항목 작성 → 엑셀 출력.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2100-05.xlsx'),
  ('L2100-07', '수입검사 관리대장', 'L-2100', '작성요령 시트 동봉.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '2_2', 'templates/standard/L2100-07.xlsx'),
  ('L2100-11', '조도관리 측정기록', 'L-2100', '조도(표면 거칠기) 측정 기록일지 — 측정값 기록 → 엑셀 출력.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '6_8', 'templates/standard/L2100-11.xlsx'),
  ('L2200-01', '연간 신뢰성 시험 계획서', 'L-2200', '제목(연도)·작성일자·작성자 + 시험 grid(8~25행 18행: 품번·품명·시험주기·시험구분[자체/외주]·검사항목·월별 계획 12·비고). 범례(외부 ○●/자체 □■) 기정의·결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2200-01.xlsx'),
  ('L2300-01', '한도견본 관리대장', 'L-2300', '견본 3행 블록 grid 5개(8:10~20:22) — 본체(관리번호·차종/모델·품명/품번·품질특성·교체주기·등록/1회 연장/2회 연장 일자) + 승인행(등록/연장 승인) + 폐기행(폐기일자·폐기사유). 결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-01.xlsx'),
  ('L2300-02', '한도 견본표', 'L-2300', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-02.xlsx'),
  ('L2300-03', '한도 견본 기준서', 'L-2300', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-03.xlsx'),
  ('L2300-04', 'OK_NG MASTER 관리대장', 'L-2300', 'OK/NG 마스터 샘플 관리대장(등록번호·유효성관리). 순번=시트 프리셋, 사진 열=시트 수기.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-04.xlsx'),
  ('L2300-05', '치구 자체 검교정 계획 및 실적', 'L-2300', '제목(연도)·작성일 + 치구 계획 grid(계획행 14블록: 품명·관리번호·규격·1~12월·비고) + 실적 grid(실적행: 1~12월). 범례(○ 계획 ● 실적)·순번은 시트 기정의.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-05.xlsx'),
  ('L2300-06', '치구 관리대장', 'L-2300', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-06.xlsx'),
  ('L2300-07', '치구 이력카드', 'L-2300', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', NULL, 'templates/standard/L2300-07.xlsx'),
  ('L3100-01', '계측기 관리대장', 'L-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-01.xlsx'),
  ('L3100-02', '계측기 이력카드', 'L-3100', '계측기 이력카드. 사진·헤더는 시트 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-02.xlsx'),
  ('L3100-03', '계측기 검교정 계획서', 'L-3100', '제목(연도)·작성일자·작성자 + 검교정 grid(7~29행 23행: 관리번호[A열 = 자동조회 키 입력]·검교정 계획 1~12월 ○●·비고). 범례(○●)·결재 서명 몫.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-03.xlsx'),
  ('L3100-04', '계측기 일상점검표', 'L-3100', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3100-04.xlsx'),
  ('L3100-05', '계측기 관리번호 부여 기준', 'L-3100', '열람형(참조 문서) — 계측기 관리번호 부여 기준: 사업부 CODE·계측기 CODE 전 칸 기정의 코드표. 기록 동선은 계측기 관리대장(L3100-01)·이력카드(L3100-02)로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('L3100-06', '검교정 합부판정 기준', 'L-3100', '열람형(참조 문서) — 검교정 합부판정 기준: 계측기명×관리 최소공차×측정불확도 판정 기준 전 칸 기정의 기준표. 기록 동선은 검교정 계획서(L3100-03)로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('L3101-01', '측정시스템 분석 계획서', 'L-3101', '부서명·작성일자·연도 + 계획/실시 2행 블록 grid 12개(6:7~28:29 — 차종·품번·품명·대상 계측기·측정 대상자·측정항목·규격 + 1~12월 ○●). NO 자동 수식(A열) 보존·범례 기정의·결재 서명 몫. MSA 연간 계획 — L-3101 측정시스템 평가 지침 연계.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3101-01.xlsx'),
  ('L3101-02', '계량형 R&R(전산)', 'L-3101', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/L3101-02.xlsx'),
  ('L4101-01', 'Xbar-R 관리도', 'L-4101', 'Xbar-R 관리도(계산기형). 최소 매핑 — 헤더 9필드만. X바/UCL/LCL 수식·측정 데이터 매트릭스·차트 = 시트 몫(수식 보존).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L4101-01.xlsx'),
  ('L4102-01', '공정능력 평가표', 'L-4102', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L4102-01.xlsx'),
  ('L4102-02', '양산단계 공정능력 산출', 'L-4102', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '9', NULL, 'templates/standard/L4102-02.xlsx'),
  ('M-1100', '생산관리 규정', 'M-1100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M-1200', '공정관리 규정', 'M-1200', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M-2100', '식별 및 추적성 관리 규정', 'M-2100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M-3100', '완성품 관리 규정', 'M-3100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, NULL),
  ('M-4100', '3정 5S활동 규정', 'M-4100', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, NULL),
  ('M-4200', '조도(Lux) 관리 지침', 'M-4200', '규정 문서(열람형) — 작성 양식이 아닌 규정 본문 등록 항목. 본문은 문서관리에서 등록·개정합니다.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, NULL),
  ('M1100-02', '설비 비가동시간 관리 대장', 'M-1100', '비가동 기록 6블록(3행 병합) grid + 전/후 검사 판정.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1100-02.xlsx'),
  ('M1100-03', '설비 비가동시간 이력관리 대장', 'M-1100', '비가동 1건 카드형(품번·LOT 전후·시간 3종·중단코드).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1100-03.xlsx'),
  ('M1100-05', '설비 비가동 주요 코드', 'M-1100', '열람형(참조 문서) — 설비 비가동 코드 정의표(E-1xx/2xx 전 행 기정의). 코드 개정은 규정 개정 절차로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1100-06', '우발사고 및 이상발생 처리 절차서', 'M-1100', '열람형(참조 문서) — 우발사고·이상발생 처리 절차서: 절차 도해 이미지 75장 문서(텍스트 4행뿐). 기록 동선은 부적합품 대장(B1100-13)·통보서(B1100-01)로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1200-01', '작업지시서', 'M-1200', '작업지시서 — 호기 구분은 시트 프리셋, 행 순서대로 기입. (생산관리 시스템이 별도로 있는 경우 그쪽 작업지시가 우선)', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-01.xlsx'),
  ('M1200-02', '열처리작업일보', 'M-1200', '열처리 작업일보 — 순서 블록 1(5행) 매핑, 블록 2~14·가열조건 SV/PV 매트릭스는 시트 몫. 열처리 공정 보유 시 사용.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-02.xlsx'),
  ('M1200-03', '주,야 인수인계 일지', 'M-1200', '주간↔야간 교대 인수인계(설비·품질·안전·자재·기타 이슈 5구분 × 양방향).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-03.xlsx'),
  ('M1200-04', '공정,납입용기 관리기준 및 수리이력', 'M-1200', '하단 수리이력 관리대장(6블록 — 용기명·규격·조치상세·금액·조치자·일자, 조치항목 4행은 시트 프리셋).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-04.xlsx'),
  ('M1200-05', '낙하품 처리 절차서', 'M-1200', '열람형(참조 문서) — 낙하품 처리 절차 본문 + PROCESS FLOW 도해(이미지)·처리 주의사항·제개정 이력 기정의. 작성 양식 아님(발생 기록은 M1200-06 낙하품 처리 관리대장으로).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1200-06', '낙하품 처리 관리대장', 'M-1200', '낙하품 발생·조치 대장(2행 블록 8건 — 본행 + 조치 상세행. 폐기/수정 □체크는 시트 수기, 상세에 조치구분 명기).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-06.xlsx'),
  ('M1200-07', '셋업품 처리 절차서', 'M-1200', '열람형(참조 문서) — 셋업품 처리 절차 본문 + 현장 사진 4(셋업품 식별표·식별 관리·성적서/보관장) 기정의. 작성 양식 아님.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M1200-08', '용접장 기준 팁 교환 주기 평가서', 'M-1200', NULL, '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M1200-08.xlsx'),
  ('M1200-09', '공정이동 전표·부자재 대사표', 'M-1200', '공정이동 전표(공정 누락 방지 — 확인란 공란 통과 금지).', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '6_11', 'templates/standard/M1200-09.xlsx'),
  ('M1200-10', '공정 자주검사 CHECK SHEET', 'M-1200', '공정 자주검사 체크시트 — 품번별 자주검사 기준·항목 작성 → 엑셀 출력.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '2_7', 'templates/standard/M1200-10.xlsx'),
  ('M1200-11', '특수공정 조건관리 CHECK SHEET', 'M-1200', '특수공정 조건관리 CHECK SHEET — 구간별 온도·보조매체(가스 등) 유량·이송 속도 등 조건 기록(3회/일 또는 초/중/종 — 품번별 관리계획서 준수). SQ 1_5·3_5 증거.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '1_5,3_5', 'templates/standard/M1200-11.xlsx'),
  ('M2100-01', 'LOT관리 기준서', 'M-2100', 'LOT 기록 규칙표(시기·장소·기록방법·담당부서 10행) 작성형. 반-MES lot_registry 와 접점.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, 'templates/standard/M2100-01.xlsx'),
  ('M2100-02', '원소재및완제품 선입선출 관리기준서', 'M-2100', '열람형(참조 문서) — 원소재·완제품 선입선출(FIFO) 규칙 기정의 완성문(적재/출하 순서도·LOT 식별표 해석방법 포함). 작성 양식 아님(점검 기록은 K2100-10 자재 보관장 점검표로).', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', NULL, NULL),
  ('M2100-10', 'LOT 추적성 대장', 'M-2100', '원자재↔완제품 LOT 추적 대장. 반-MES lot_registry 역추적과 접점.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '5_1', 'templates/standard/M2100-10.xlsx'),
  ('M3100-01', '출하관리대장', 'M-3100', '출하 기록 대장(차종·품번·수량·LOT·출하일자·출하 점검 4항목 ○/×). 출하검사 성적서(M3100-05)와 세트.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '영업팀', '8', NULL, 'templates/standard/M3100-01.xlsx'),
  ('M3100-05', '완성품·출하검사 성적서', 'M-3100', '검사 업무 책임=품질보증팀.', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '8', '2_8', 'templates/standard/M3100-05.xlsx'),
  ('M3100-06', '용기·적재 표준화 기준표', 'M-3100', '품번별 용기·적재 표준 기준표(장입수·단수·식별·청정도·라벨).', '[]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '8', '5_4', 'templates/standard/M3100-06.xlsx'),
  ('M4100-01', '사무용 3정 5S 진단 SHEET', 'M-4100', '사무용 3정 5S 진단 SHEET. 소계(T33) 수식 보존.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-01.xlsx'),
  ('M4100-02', '현장용 3정 5S 진단 SHEET', 'M-4100', '현장용 3정 5S 진단 SHEET. M4100-01 동형.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-02.xlsx'),
  ('M4100-03', '3정 5S 평가 보고서', 'M-4100', '3정 5S 평가 보고서. 평가요소 5블록(정리·정돈·청소·청결·습관화) 시정및건의/비고 + 종합의견 문서형 매핑.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-03.xlsx'),
  ('M4100-04', '3정 5S 평가지적 및 시정대책서', 'M-4100', '3정 5S 지적 및 시정 대책서. 지적사항/개선전·시정대책/개선후 문서형 매핑. 본문 인사말(7~8행)은 시트 프리셋.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, 'templates/standard/M4100-04.xlsx'),
  ('M4100-05', '3정5S 관리 구역도', 'M-4100', '열람형(참조 문서) — 3정5S 관리 구역도: 사업부별 구역도 이미지 6면 문서. 기록 동선은 진단 SHEET(M4100-01/02)·평가 보고서(M4100-03)로.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '생산팀', '7', NULL, NULL),
  ('M4200-01', '조도측정 체크시트', 'M-4200', '조도 측정 체크시트 — 공정별 측정값(을지-1·을지-2) 기록. 측정 기준(로트·주기)은 시트 프리셋.', '["담당","팀장","사업부장"]', NULL, NULL, NULL, NULL, '공통', 0, NULL, NULL, '품질보증팀', '7', NULL, 'templates/standard/M4200-01.xlsx');
