/**
 * SQ 백본 전처리 스크립트
 *
 * 입력: ../코워크 작업한거 모음/sq_master_map.json  (코워크가 만든 SQ Ver4 백본)
 *       ../코워크 작업한거 모음/rules.json           (qms_sqmap 규정↔SQ 매핑)
 * 출력: resources/migrations/0012_sq_backbone.sql   (자동 생성 시드 SQL)
 *
 * 삼보모터스(HKMC) SQ 평가 Ver4(브레이징용접): 6 카테고리 / 42 항목 / 1000점.
 * forms.reg_code('B-1100') == qms_sqmap 키 → SQ항목 으로 218개 양식 전부가 SQ에 연결됨.
 * 0006(preprocess-bom.mjs CSV→SQL)과 동일한 빌드타임 생성 패턴.
 */
import { readFileSync, writeFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, '..')
const coworkDir = join(projectRoot, '..', '코워크 작업한거 모음')
const mapPath = join(coworkDir, 'sq_master_map.json')
const rulesPath = join(coworkDir, 'rules.json')
const outSqlPath = join(projectRoot, 'resources', 'migrations', '0012_sq_backbone.sql')

function sqlEscape(s) {
  if (s === null || s === undefined) return 'NULL'
  return `'${String(s).replace(/'/g, "''")}'`
}

// ───── 입력 로드 (UTF-8 + BOM 제거) ─────
const map = JSON.parse(readFileSync(mapPath, 'utf-8').replace(/^﻿/, ''))
const rules = JSON.parse(readFileSync(rulesPath, 'utf-8').replace(/^﻿/, ''))

const categories = map.categories || []
const qmsSqmap = rules.qms_sqmap || {}

// ───── 구조화 ─────
const catRows = []
const itemRows = []
const itemDocRows = []
const itemFormTypeRows = []
let itemSort = 0

categories.forEach((cat, ci) => {
  catRows.push({
    id: cat.id,
    name: cat.name,
    points: cat.points,
    iatfClause: cat.iatf_clause ?? null,
    sortOrder: ci
  })
  for (const it of cat.items || []) {
    itemRows.push({
      code: it.code,
      categoryId: cat.id,
      title: it.title,
      points: it.points ?? 0,
      requirement: it.requirement ?? null,
      sortOrder: itemSort++
    })
    for (const g of it.governing_documents || []) {
      itemDocRows.push({
        itemCode: it.code,
        docCode: g.code ?? null,
        docName: g.name ?? null,
        dept: g.dept ?? null
      })
    }
    for (const rf of it.required_forms || []) {
      itemFormTypeRows.push({
        itemCode: it.code,
        formType: rf.form_type,
        countInArchive: rf.count_in_archive ?? 0
      })
    }
  }
})

// reg_code ↔ SQ항목 (qms_sqmap 역정규화) — 핵심 JOIN 다리
const regMapRows = []
for (const [regCode, itemCodes] of Object.entries(qmsSqmap)) {
  for (const ic of itemCodes) regMapRows.push({ regCode, itemCode: ic })
}

const totalPoints = catRows.reduce((s, c) => s + (c.points || 0), 0)

// ───── SQL 생성 ─────
const lines = []
lines.push('-- ============================================================')
lines.push(`-- Migration 0012: SQ 평가 백본 (${catRows.length} 카테고리 / ${itemRows.length} 항목 / ${totalPoints}점)`)
lines.push('--')
lines.push('-- AUTO-GENERATED by scripts/preprocess-sq.mjs')
lines.push('-- Source: 코워크 작업한거 모음/{sq_master_map.json, rules.json}')
lines.push(`-- Standard: ${map.meta?.standard ?? ''}`)
lines.push('--')
lines.push('-- forms.reg_code ↔ sq_reg_map.reg_code 로 218개 양식이 SQ 42항목에 자동 연결됨.')
lines.push('-- Idempotent: 재실행 안전(DROP 먼저).')
lines.push('-- ============================================================')
lines.push('')
lines.push('DROP TABLE IF EXISTS sq_item_form_types;')
lines.push('DROP TABLE IF EXISTS sq_item_docs;')
lines.push('DROP TABLE IF EXISTS sq_reg_map;')
lines.push('DROP TABLE IF EXISTS sq_items;')
lines.push('DROP TABLE IF EXISTS sq_categories;')
lines.push('')
lines.push('CREATE TABLE sq_categories (')
lines.push('  id          INTEGER PRIMARY KEY,')
lines.push('  name        TEXT NOT NULL,')
lines.push('  points      INTEGER NOT NULL,')
lines.push('  iatf_clause TEXT,')
lines.push('  sort_order  INTEGER NOT NULL DEFAULT 0')
lines.push(');')
lines.push('')
lines.push('CREATE TABLE sq_items (')
lines.push('  code        TEXT PRIMARY KEY,          -- 대제목_세부번호 (예 2_7)')
lines.push('  category_id INTEGER NOT NULL,')
lines.push('  title       TEXT NOT NULL,')
lines.push('  points      INTEGER NOT NULL,')
lines.push('  requirement TEXT,')
lines.push('  sort_order  INTEGER NOT NULL DEFAULT 0,')
lines.push('  FOREIGN KEY (category_id) REFERENCES sq_categories(id)')
lines.push(');')
lines.push('CREATE INDEX idx_sqitem_cat ON sq_items(category_id, sort_order);')
lines.push('')
lines.push('CREATE TABLE sq_reg_map (')
lines.push('  reg_code  TEXT NOT NULL,               -- forms.reg_code 와 동일 도메인 (예 B-1100)')
lines.push('  item_code TEXT NOT NULL,')
lines.push('  PRIMARY KEY (reg_code, item_code),')
lines.push('  FOREIGN KEY (item_code) REFERENCES sq_items(code)')
lines.push(');')
lines.push('CREATE INDEX idx_sqregmap_reg ON sq_reg_map(reg_code);')
lines.push('')
lines.push('CREATE TABLE sq_item_docs (')
lines.push('  id        INTEGER PRIMARY KEY AUTOINCREMENT,')
lines.push('  item_code TEXT NOT NULL,')
lines.push('  doc_code  TEXT,')
lines.push('  doc_name  TEXT,')
lines.push('  dept      TEXT,')
lines.push('  FOREIGN KEY (item_code) REFERENCES sq_items(code)')
lines.push(');')
lines.push('CREATE INDEX idx_sqitemdoc_item ON sq_item_docs(item_code);')
lines.push('')
lines.push('CREATE TABLE sq_item_form_types (')
lines.push('  id               INTEGER PRIMARY KEY AUTOINCREMENT,')
lines.push('  item_code        TEXT NOT NULL,')
lines.push('  form_type        TEXT NOT NULL,')
lines.push('  count_in_archive INTEGER NOT NULL DEFAULT 0,')
lines.push('  FOREIGN KEY (item_code) REFERENCES sq_items(code)')
lines.push(');')
lines.push('CREATE INDEX idx_sqitemft_item ON sq_item_form_types(item_code);')
lines.push('')

lines.push(`-- ───── SEED: ${catRows.length} Categories ─────`)
for (const c of catRows) {
  lines.push(
    `INSERT INTO sq_categories (id, name, points, iatf_clause, sort_order) VALUES (` +
    `${c.id}, ${sqlEscape(c.name)}, ${c.points}, ${sqlEscape(c.iatfClause)}, ${c.sortOrder});`
  )
}
lines.push('')
lines.push(`-- ───── SEED: ${itemRows.length} Items ─────`)
for (const it of itemRows) {
  lines.push(
    `INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES (` +
    `${sqlEscape(it.code)}, ${it.categoryId}, ${sqlEscape(it.title)}, ${it.points}, ` +
    `${sqlEscape(it.requirement)}, ${it.sortOrder});`
  )
}
lines.push('')
lines.push(`-- ───── SEED: ${regMapRows.length} reg_code↔item (qms_sqmap) ─────`)
for (const r of regMapRows) {
  lines.push(
    `INSERT INTO sq_reg_map (reg_code, item_code) VALUES (${sqlEscape(r.regCode)}, ${sqlEscape(r.itemCode)});`
  )
}
lines.push('')
lines.push(`-- ───── SEED: ${itemDocRows.length} 지배규정 ─────`)
for (const d of itemDocRows) {
  lines.push(
    `INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES (` +
    `${sqlEscape(d.itemCode)}, ${sqlEscape(d.docCode)}, ${sqlEscape(d.docName)}, ${sqlEscape(d.dept)});`
  )
}
lines.push('')
lines.push(`-- ───── SEED: ${itemFormTypeRows.length} 기대 양식유형 ─────`)
for (const ft of itemFormTypeRows) {
  lines.push(
    `INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES (` +
    `${sqlEscape(ft.itemCode)}, ${sqlEscape(ft.formType)}, ${ft.countInArchive});`
  )
}
lines.push('')

writeFileSync(outSqlPath, lines.join('\n'), 'utf-8')

console.log(`✓ 0012 마이그레이션 생성 완료: ${outSqlPath}`)
console.log(`  - 카테고리: ${catRows.length}건 (합계 ${totalPoints}점)`)
console.log(`  - 항목: ${itemRows.length}건`)
console.log(`  - reg_code↔item: ${regMapRows.length}건`)
console.log(`  - 지배규정: ${itemDocRows.length}건`)
console.log(`  - 기대 양식유형: ${itemFormTypeRows.length}건`)
