-- ============================================================
-- Migration 0012: SQ 평가 백본 (6 카테고리 / 42 항목 / 1000점)
--
-- AUTO-GENERATED by scripts/preprocess-sq.mjs
-- Source: 코워크 작업한거 모음/{sq_master_map.json, rules.json}
-- Standard: 삼보모터스(HKMC) SQ 평가 Ver4 - 브레이징용접 업종
--
-- forms.reg_code ↔ sq_reg_map.reg_code 로 218개 양식이 SQ 42항목에 자동 연결됨.
-- Idempotent: 재실행 안전(DROP 먼저).
-- ============================================================

DROP TABLE IF EXISTS sq_item_form_types;
DROP TABLE IF EXISTS sq_item_docs;
DROP TABLE IF EXISTS sq_reg_map;
DROP TABLE IF EXISTS sq_items;
DROP TABLE IF EXISTS sq_categories;

CREATE TABLE sq_categories (
  id          INTEGER PRIMARY KEY,
  name        TEXT NOT NULL,
  points      INTEGER NOT NULL,
  iatf_clause TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE sq_items (
  code        TEXT PRIMARY KEY,          -- 대제목_세부번호 (예 2_7)
  category_id INTEGER NOT NULL,
  title       TEXT NOT NULL,
  points      INTEGER NOT NULL,
  requirement TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (category_id) REFERENCES sq_categories(id)
);
CREATE INDEX idx_sqitem_cat ON sq_items(category_id, sort_order);

CREATE TABLE sq_reg_map (
  reg_code  TEXT NOT NULL,               -- forms.reg_code 와 동일 도메인 (예 B-1100)
  item_code TEXT NOT NULL,
  PRIMARY KEY (reg_code, item_code),
  FOREIGN KEY (item_code) REFERENCES sq_items(code)
);
CREATE INDEX idx_sqregmap_reg ON sq_reg_map(reg_code);

CREATE TABLE sq_item_docs (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  item_code TEXT NOT NULL,
  doc_code  TEXT,
  doc_name  TEXT,
  dept      TEXT,
  FOREIGN KEY (item_code) REFERENCES sq_items(code)
);
CREATE INDEX idx_sqitemdoc_item ON sq_item_docs(item_code);

CREATE TABLE sq_item_form_types (
  id               INTEGER PRIMARY KEY AUTOINCREMENT,
  item_code        TEXT NOT NULL,
  form_type        TEXT NOT NULL,
  count_in_archive INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (item_code) REFERENCES sq_items(code)
);
CREATE INDEX idx_sqitemft_item ON sq_item_form_types(item_code);

-- ───── SEED: 6 Categories ─────
INSERT INTO sq_categories (id, name, points, iatf_clause, sort_order) VALUES (1, '생산조건관리', 120, '8.5 생산/서비스 제공 (작업표준, Control Plan)', 0);
INSERT INTO sq_categories (id, name, points, iatf_clause, sort_order) VALUES (2, '검사시험', 310, '8.6 제품/서비스 출시, 7.1.5 모니터링·측정자원', 1);
INSERT INTO sq_categories (id, name, points, iatf_clause, sort_order) VALUES (3, '설비관리', 180, '7.1.3 기반시설, 8.5.1 생산설비 관리', 2);
INSERT INTO sq_categories (id, name, points, iatf_clause, sort_order) VALUES (4, '금형관리', 100, '8.5.1.5 TPM, 7.1.3.1 공장·설비·장비', 3);
INSERT INTO sq_categories (id, name, points, iatf_clause, sort_order) VALUES (5, '자재관리', 90, '8.5.4 보존, 8.5.2 식별·추적성', 4);
INSERT INTO sq_categories (id, name, points, iatf_clause, sort_order) VALUES (6, '품질경영체제', 200, '4~10 전반 (4M변경 6.3, 부적합 8.7, 역량 7.2)', 5);

-- ───── SEED: 42 Items ─────
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('1_1', 1, '표준류 작성 및 준수상태', 20, '- 표준류(관리계획서, 작업표준서, 설비일상점검표 등)와 실제공정 일치성 확인[관리 분담 등]
    - 고객과 협의된 검사협정서/검사기준서 기준과 실제 업무절차 일치성
    - 공정 FMEA작성 및 주요 품질 문서 내용과 연계상태 확인
    - 주요 표준류(작업표준서 등) 현장내 게시 상태
    - 관리계획서 및 현장내 표준류 중요공정/안전 보안공정 식별표시관리
    - 신규/임시작업자 공정투입전 업무 R&R 명확화, 단계별 작업표준서 게시 및 전문용어 사용지양
    - 공정내 사용되는 설비 및 부자재등은 사전 검증을 통해 표준류 반영되어야 하며 미승인 설비 및 부자재 사용 금지
       ex) 조립성 확보를 위한 미승인 열풍기 및 윤활재 사용등', 0);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('1_2', 1, '설비 가동중단(계획/비계획)후 재가동시 업무처리 절차 수립 및 준수상태', 20, '- 설비 가동중단 발생시 설비점검 절차 수립 및 준수상태
      ※ 계획 : 가동중단 시간별/사유별 점검절차 수립 및 이행
         비계획 : 이상발생 가동중단 발생시 설비 점검 지침, 생산중인 제품에 대한 품질보증 업무절차 수립 및 이행
    - 설비중단/이상 발생시(툴교환 포함) 직전 생산품 이상유무 검사 및 설비이상 조치후 초품 이상유무 검사 및 기록관리
       (설비중단/이상 발생시 또는 설비이상 조치중 생산부품 불량으로 폐기 및 수량 이력관리)
    - 비계획 가동중단 발생시 전/후 생산제품에 대한 LOT 구분 관리방안 수립 및 식별관리 실시', 1);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('1_3', 1, '외국인 배치 운영공정 현지어 번역/게시된 표준류 반영상태', 10, '- 작업표준서, 설비일상점검 기준표, 작업일보 등 외국인 배치공정 표준류 현지어 번역 게시상태
      : 부적합 처리절차 및 중요 품질문제 개선 사례등 품질의식 강화목적 표준류 번역 게시 (추가 관리시 우수)
      ※ 해당공정 외국인작업자 주요 표준류 교육 및 내용 숙지 시 현지어 번역게시 불필요(현장확인 필요)', 2);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('1_4', 1, '품질관리 취약 시간대 관리기준 수립 및 관리상태 (주말특근 및 비지정 작업자 투입시포함)', 20, '- 교대 작업시 일상점검, 자주검사 및 순회검사 관리기준 수립 및 관리상태
    - 교대 작업시 공정 Issue 사항 전달 여부
      ※ 초/종품 검사는 필수, 중품은 선택사항으로 자율적 기준 수립필요, 중품검사 미진행도 가능,
          단, 생산LOT가 장기적일경우 최소 1회/shift검사 진행 필요
      ※ 인원 부족으로 야간 검사요원 미 투입 시 야간 생산품 검증 프로세스 수립
          (야간 작업 초종 생산품 익일 주간 검사인원 출근시 검사 등)', 3);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('1_5', 1, '주요조건 기준수립 및 현장 관리 상태 비교검증 실시', 50, '(로 브레이징)
   ▷ 가 용접 : 전류.전압.유량
   ▷ 주요조건 : 사양별 소재 장입량, 온도, 시간(콘베어속도). 용재량(동링.솔더)확인
   ▷ 로내 구간별 온도 실측관리    - 온도 타점기록계 관리 / 온도 프로파일 관리
   ▷ 로내 질소가스 비율 관리 기준 설정 및 준수상태
(수동 브레이징 용접)
   ▷ 용접 표준서 게시 (온도. 한도견본)
   ▷ 용접 작업자 인증 . 용접 검사로 보증
   ▷ 겹침 모재 적정틈새 유지 관리
   ▷ 용접조건 기준관리
    → 용접 조건 관리항목 : 가스 유량 경보장치 설치 미설치시 관리방안 수립 및 기준준수, 실행상태

※ 작업자 착용장갑에 의한 제품 오염(실오라기 등)으로 용접부 리크 발생이 없도록 점검', 4);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_1', 2, '수입검사 실시기준 수립 및 준수상태', 40, '- 검사협정서/기준서 체결상태(사급품은 1차 협력사가 체결한 검사협정서 사본 접수 및 동일 시료/주기로 검사 실시 필요)
        → 검사협정 체결이 어려울 시 검사기준서 수립으로 대체 (예: 대기업 공급 원재료,도금업종 등)
    - 외주품 입고 시 외주사 출하성적서 접수 및 수입검사 실측값 비교검증 여부
    - 원재료 M/SHEET 접수 시 물성 및 화학조성비 합/부 판단기준 명확화 수립
    - 입고 LOT와 출하검사 성적서내 LOT 일치성 확보여부(원소재의 경우 M/SHEET내 검사시료 LOT 일치성)
    - 검사협정서/기준서에 준한 일상검사/정기검사 실시상태
    - 용기/포장 적정성 (필요시 제전 비닐/박스, 이물질 유입 방지, 제품간 간섭 방지,
       물류 이동시 제품 훼손 방지,사양 식별, 오조립 방지, 이물질 유입방지, 체결부 좌면상태, 취급 용이성)
       및 습동부/매칭부 단품 치수검사 상태
    - 다 CAVITY 제품의 경우 CAVITY별 검사 기준 수립 및 준수 상태
      ※ 점검기준은 CAVITY 총 수량 고려 합리적인 점검주기 설정(일상/정기) 및 이행필요
          예) 일상 : 10 캐비티↓ : 전캐비티 검사,  11 캐비티↑ : 홀수일 Lot 홀수 캐비티/짝수일 Lot 짝수 캐비티 검사
               정기 : 전 캐비티 검사', 5);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_2', 2, '수입검사 누락방지 절차 수립(수입검사 대장 LIST 작성) 및 준수 상태', 30, '- 외주품 입고시 수입검사 마스터 관리 대장 작성을 통한 검사 누락 예방
    - 수입검사 실시 전 외주품/원재료 입고처리 안되도록 업무 프로세스 수립
    - 수입검사 완료품 식별 프로세스 수립 (합격도장 등)', 6);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_3', 2, '검사용 마스터(한도견본) 관리기준 수립 및 준수상태', 20, '- 외주품/완성품 외관 합/부 판별용 한도견본 운영 (용접제품 표면관리 기준 설정-스패터,Chip,버어, 이물질)
    - 설비 유효성 확보용 한도견본 또는 셋팅 마스터지그 제작관리 (시업시 마스터 이용한 설비 유효성 검증 실시)
    - 검사기 신뢰도 확인을 위한 OK/NG 마스터 설정기준 및 관리상태
    - 한도견본의 변색, 변형, 녹 발생 등으로 실제 견본품 운영이 어려울 경우 외관검사기준서로 대체 가능
    - 목시검사(확대경) 한도견본 비치, 관리 및 이력관리', 7);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_4', 2, '정기검사(신뢰성 시험 포함) 실시계획 수립 및 준수상태 (실시결과 신뢰성 확보 요구됨)', 30, '- 정기 시험 성적서 신뢰도 확보
      (성적서 시험 전/후 사진 첨부, 사진內 시험 날짜표시, 계측기 전산 연동시 원본데이터 저장관리 등)
    - 환경규제(중금속) 정기시험 실시상태 : 검사협정 체결기준 시험결과 증빙관리 상태
      (시험장비 보유시 자체 성적서 인정, 미보유시 1차사 또는 공인기관 의뢰 가능)', 8);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_5', 2, '계측기/검사구 보유 및 신뢰성 확보상태 (검교정 주기설정, 교정상태)', 20, '- 검사협정 체결기준 시험항목 자체시험 가능한 계측장비 보유상태 (정기 신뢰성 항목별 계측기 지정 및 준수필요)
      ※ 고가 계측기 등 자체검증 불가능 시험 항목의 경우 1차 협력사 또는 공인기관시험 인정
          (예 : 3차원 측정기, 성분분석기 등)되나 시험결과 접수 및 이상발생 여부 검토 필요
    - 계측기 검교정 계획 대비 실적관리 상태 (계측기 검교정 성적서/테그 관리)
      ※ 검교정 자격인증 인원 보유 협력사는 자체 검증 근거 확보시 인정
    - 주요 검사구 유효성 확보여부 점검결과
         예) 사출품 측정용 검사구 3차원 데이터 측정결과, 치수 보증된 제품을 통한 자체 비교검증 데이터 등', 9);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_6', 2, '게이지 R&R 실시기준 수립 및 준수 상태', 20, '- 계측기 운영 기준별 R&R 평가 계획 수립
       (자체제작 전용 계측기는 필히 실시할 것. 단. 자동 측정 검사 장비 제외 : 비커스경도기, 거칠기 측정기 등)
    - 계측 장비별 실제 사용인력(작업자/검사원) 계량형  R&R 검증 진행 데이터', 10);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_7', 2, '제품별 자주검사/순회검사 기준 설정 및 준수상태, DATA 관리', 50, '- 초/종품 외관, 치수 (검사지그 활용)    - 샘플 실측 요망
    - 용접검사 : 외관. 타격검사. 절단검사. 기밀성(리크 검사)
    - QC순회검사: 작업자 자주검사 실시상태 확인 및 주요 포인트 추가 검사 후 확인 서명', 11);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_8', 2, '완제품 검사 기준 설정 및 준수상태', 50, '- 외관, 치수, 취약부 절단면 검사, 상대 물 조립 성 검증 등 (샘플 실측 요망)
    - 최종 검사 기준설정 및 시행상태, 검사이력 관리 (1회 이상 /3개월)
    → 브레이징 용접 : 용접부 용입성 평가 (절개 평가) 및 외관 크랙 및 LEAK 검사 진행', 12);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('2_9', 2, '수정 리워크 및 후공정에서 발견 불가한 품질 관리항목(리크. 용접) 점검기준 설정 및 실행상태, 이력관리', 50, '- 수정 후 재검사 실시 및 이력관리 (재 리크 검사)
    - 후공정에서 발견 불가한 품질 관리항목(리크. 용접) 점검기준 설정 및 실행상태, 이력관리 (필드문제 예방)', 13);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('3_1', 3, '설비 일상점검 업무절차 수립 및 준수여부', 30, '- 설비별 설비일상 점검부위 및 점검방법 도식화 관리상태
    - 설비내 부착 게이지류 상/하한 식별 및 측정 실측값 일상점검표 기록관리
    - 설비내 F/P설비 경고등/알람 정상작동 및 설비내 셋팅값/관리공차 표준과 일치여부
    - 설비 셋팅값 임의조작 방지를 위한 시건장치/KEY-LOCK 반영상태
    - 주요 핵심설비 시업시 설비 정상작동 여부 검증 프로세스 수립(OK/NG 마스터 점검 또는 계측값 셋팅용 게이지 점검)
    - 캘리브레이션이 필요한 생산 및 검사장비는 시업전 0점 조정(티칭)후 이상유무(OK/NG마스터를 활용)를 검증 필요', 14);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('3_2', 3, '설비 정기점검 업무절차 수립 및 준수여부', 30, '- 주요 핵심설비 정기점검 계획수립 및 점검상태(외주업체 정도점검 성적서 포함, 자체점검주기 반영)
        (외주업체 또는 자체 정도점검 가능 설비/인력이 확보된경우 인정)
    - 설비내 소모성 부자재류 점검/교체주기 설정 및 준수여부
        [필요시 소모성 부자재 교체주기 설정근거 제시 필요, T/O 이력 등]
    - 설비 부착 센서 및 게이지류에 대한 정도 보증 방안 수립 및 이행 상태
      1) 설비내 주요 압력계 정기점검 정도보증 또는 검교정된 마스터게이지 비교 검증활동 실시
      2) 금형내 노즐온도 센서 등 중요 센서류 고장여부 정기점검시 정도보증 활동 필요
          (단, 부품생산 금형 미보유 업종 제외 - 예)전기조립, 스프레이도장, 사출금형, 프레스금형, 프레스 등)
      3) 전동툴 및 너트런너 점검주기 설정 및 정기적 토크 검사 진행
      ※ 설비 일상점검 항목을 제외한 세부 점검 필요부만 정기점검 계획 수립 및 점검 필요', 15);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('3_3', 3, '용접공정 제품안착, JIG 기준핀, 기준면 점검기준 수립, 점검시행 여부', 20, '- 제품 안착 여부 F/PROOF 구축시 점검기준, 관리상태 및 F/P 미구축시 관리방안 수립 및 실시 내용 확인
    - 마모 및 유격 없을 것 (부품 안착 후 유격 없을 것) 스팩터 없을것 (스팩터 제거후 작업)
    - 클렘프 작동상태. 센서 류 작동상태.에어 누기', 16);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('3_4', 3, '작업전 설비 일상점검 항목 설정 및 실행상태 확인', 30, '- 용접기: 팁 교환. 노즐청소. 와이어 공급기. 케이블. 전류 전압.
    - 브레이징 로 : 로 내부온도 . 콘베어 속도 실측 . 가스유량 .메쉬망
    - 로봇 원점관리 : 로봇 용접 시작원점 일치 확인. 궤적 확인
     (시업전 원점확인/ 사진 전산관리 or 경보작동 : 원점확인 수치화 어려움)', 17);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('3_5', 3, '브레이징 로 점검 항목 설정상태 및 시행 여부', 20, '- 브레이징 로내 온도 구간별 실측점검
    - 온도 프로파일 관리
    - 로 콘베어 메쉬 속도 실측점검', 18);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('3_6', 3, '전극, 가스잔량, 냉각수 온도 F/PROOF 구축, 미구축시 관리기준 수립 및 이행 상태', 30, '- 전극, 가스, 냉각수 관리 F/PROOF 구축시 관리기준 및 준수상태, F/PROOF 미구축시 관리기준 수립여부,
       기준준수 및 이행상태
       (드레싱 및 교체 주기 관리, 용접타점 관리, 타점 도달시 경보장치)
    - 가스잔량관리 : 가스탱크내 잔량 또는 가스탱크압력 부족시 경보작동
      ※ 개별 가스탱크 사용 용접기 잔량 F/PROOF 설치 불요
    - 단, 가스탱크 2개이상 병렬연결 사용시 잔량 관리방안 수립 필요', 19);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('3_7', 3, '용접 지그 점검주기, 관리주기 설정 및 이행상태', 20, '- JIG 기준 핀 외경치수 측정 (관리범위 이탈방지)
    - 주기 : 소재, 과거 데이터 고려하여 합리적 주기 설정(1회/분기 이상 권장)
      ※ 자체 측정주기 설정시 설정근거 마련 안전율 80%
    - 지그 기준면 마모/유격
    - 지그 안착상태 부품 유격발생 여부 점검 (시업전 / 지그 수리 보전시)
    - 클렘프 고정상태. 센서 류 고정 작동상태.배선정리 피복점검', 20);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('4_1', 4, '금형 일상/정기점검 프로세스 수립 및 준수상태', 30, '<일상점검 : 일상점검 체크시트 운영>
    - 금형 청결 및 점검기준 (금형 상/하부 이물질, 손상, 볼트풀림, 도금상태, 마모, 핀 유격, 스크랩 취출상태) 수립 및 시행 여부
   <정기점검 : 정기점검 체크시트 운영>
    - 금형별 타발수 기록/관리 상태(정기적인 실적점검 실적)
        → 전산관리 또는 엑셀 등 활용한 타발수 실적관리 데이터 유효성 확보여부 점검
            (설비내 카운터 또는 생산일보 실적 기준으로 타발수 관리 필요,   ※ 출하수량 기준으로 타발수 관리시 감점 실시)
    - 금형별 등급관리기준 수립 및 등급기준에 따라 정기점검 주기설정 및 준수상태
      : 프레스 밴딩금형 가이드핀/가이드 유동방지장치 적용 및 이상유무 점검
    - 타발수 기준 프레스금형 오버홀 (다이 평행도, 평탄도 검사 및 교체)
    - 금형설치후 연속생산은 금형 연마, 소모품교체, 정기점검 주기를 준수할 수있는 범위내에서 생산계획 수립
      ※ 자체 프레스 공정이 없는경우 미해당으로 표기', 21);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('4_2', 4, '금형 세척관리 프로세스 수립 및 준수상태', 30, '- 현장내 세척관리기준 작성/게시 및 별도 체크시트 운영 (절차서, 장비현황, 인원 등)
    - 금형별 등급별 세척 기준 설정 및 준수상태 [점검 타발수 도달 전 세척관리 활동 가능토록 업무절차 수립 필요]
      ※ 자체 프레스 공정이 없는경우 미해당으로 표기', 22);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('4_3', 4, '금형 보전 프로세스 수립 및 준수상태', 20, '- 금형 수리이력 관리대장 (금형 Shot수 이력)
    - 금형 수정사항 발생시 협력사 임의수정 금지 (금형제작사에 정식 수정요청 必)
      ※ 자체 프레스 공정이 없는경우 미해당으로 표기
    - 금형 수정 초품에 대한 검사 이력 관리', 23);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('4_4', 4, '금형 보관 프로세스 수립 및 준수상태', 10, '- 금형보관대 제작 및 금형위치 현황판 주소화 관리(공정투입/작업대기/외주수리 등 LOCATION별 관리여부)
    - 금형 식별관리 절차 수립 및 준수(양산, A/S차종 등)
    - 금형 보관시 이물유입 방지 대책 수립 및 세척상태 보관 등 관리실태 현장 점검
      ※ 자체 프레스 공정이 없는경우 미해당으로 표기', 24);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('4_5', 4, '금형 이관 프로세스 수립 및 준수상태', 10, '- 신규제작 및 양산 금형 이관시 T/OUT 성형 검증 실시(실시결과 증빙관리)
      ※ 자체 프레스 공정이 없는경우 미해당으로 표기', 25);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('5_1', 5, '원자재 및 재공품, 출하품 LOT 추적성 관리 프로세스 수립 및 준수상태', 30, '[CASE1] LOT수작업관리 - 파렛트or 부품단위
   ▷ 보안/안전 부품 별도 식별 표시 : LOT타각, 식별마크 등
   ▷ 선입/선출 관리기준 유무 (공정~출하) - 관리 대장, 레이아웃
   ▷ 선입 선출 준수 여부 - 중요 부품 샘플링 점검, 인라인 투입 제품, 투입 대기 제품, 자재창고 적재 제품 생산일 점검
   ▷ 부품 LOT 표기 여부  (표준류 지정시) - 각인, 스티커, 타각 등
   ▷ 부품 LOT기록 마스터리스트 관리되고 역추적 가능 여부
 [CASE2] LOT전산관리 - 파렛트단위
   ▷ 파렛트 납품단위 이종 LOT 생산품 혼입 방지 프로세스 수립 - 파렛트 납입 제품 혼입여부 실물 확인
   ▷ 파렛트 바코드 라벨 부착 관리 여부 (바코드 라벨 유실 방지 대책 포함)
    - 생산 LOT 정보 포함, 보안/안전 부품 별도 식별 표시
   ▷ 파렛트 단위 공정 투입시 바코드 리딩     - 미리딩 오류 발생 알람 및 선입선출 인터락 유무
   ▷ 파렛트 단위 LOT 전산 관리되고, 역추적 가능 여부
[CASE3] LOT전산관리 - 부품단위
   ▷ 부품 바코드 라벨 부착 관리 여부 (바코드 라벨 유실 방지 대책 포함)
    - 생산 LOT 정보 포함, 보안/안전 부품 별도 식별 표시
    - 라벨 부착 위치는 정해져 있으며, 불완전 부착에 의한 상대물 간섭 없을것
   ▷ 부품단위 공정 투입시 바코드 리딩 - 미리딩 오류 발생 알람 및 선입선출 인터락 유무
   ▷ 부품 단위 LOT 전산 관리되고, 역추적 가능 여부', 26);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('5_2', 5, '수입자재 보관장 관리기준 수립 및 준수상태', 20, '- 자재 창고 Lay Out 현황도 작성 및 선입선출 관리(선입선출 다이 등 구조적 시스템, 입/불출 절차 효율성 확보 여부)
    - 입고품 적재/관리기준 수립 및 준수(입고 완료품 찍힘/발청, 이물질오염, 기타 손상 확인시 감점)
    - 원소재 보관 관리기준 수립 및 준수상태(포장상태 및 개봉후 식별방법 등)
    - 미사용 장기보관 자재류 처리기준 수립 및 이행상태
    - 설변에 의한 불용자재 발생시 자재 식별 및 혼입 방지 관리 상태
    - 항온/항습보관 필요 자재의 경우 보관장 관리기준 수립 및 준수 상태
    - 원소재 및 외주품 안전재고 관리기준 수립 및 외주품 결품시 유사사양 대체 투입 금지', 27);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('5_3', 5, '입고품 식별관리 기준 수립 및 준수여부', 20, '- 검사 전,후 식별 및 미검사품 사용 방지 보증 방안
    - 소재사양 및 GRADE 식별절차
    - 장기/불용/개발품 자재 식별절차(장기/불용/개발용 원재료 별도 구분/식별관리)
    - 공정 투입후 잔량관리(보관상태/식별표시/유효기간 설정 등)
    - 여러 사양의 부품을 동시 생산하는 라인의 SUB품 조립 작업시 사양관리 방안마련
     ※ Barcode 인터락 또는 부품 보관박스 LABEL 구분후 작업일보 SUB품 사양(품번기입) 활동으로 정사양 여부 시업전 점검', 28);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('5_4', 5, '재공품/완제품 용기 표준화 관리기준 수립 및 이행상태', 20, '- 품목별/공정별 장입(적재) 기준 수립 및 준수상태/ 과다적재 예방을 위한 장입 한계 기준설정 등
    - 외관확인이 어려운 공정처리 전/후 재공품 보관용기 식별절차 수립 및 준수상태
        (예: 표면처리, 열처리 전/후, 템퍼링 전/후 용기 식별관리 절차수립, 열처리후 템퍼링 시간관리)
    - 제품 특성을 고려한 용기 관리기준 설정(청정도 관리 대상품 이물질유입 예방목적 용기 세척, 오염방지 커버 적용 등)
    - 포장 용기 다단적재 및 현장 적재상태 (종이BOX, 프라스틱BOX, 전용용기 등 적재 관리기준 수립 및 이행상태)
    - 완제품 보관관리 기준 및 관리상태
      : 성적서 기록상태, 완제품 보관관리(별도공간/식별공간, 청결관리, 간지사용 등 제품 외관 및 기능에 품질문제 발생
        가능여부)', 29);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_1', 6, '안전사고 발생 예방을 위한 업무 프로세스 수립 및 준수실태', 30, '- 작업자 안전관리 프로세스 수립 및 준수실태(현장확인)
      : 생산중 핸드폰 미사용을 위한 별도 보관대 설치 및 시건장치, 라인투입전 휴대폰 미반납후 사용시 조치방안
       : 안전 보호장구(보안경/헬멧/장갑 등) 착용 기준수립 및 이행상태 점검(일상)
    - 업종별 안전사고 발생 예방을 위한 설비/레이아웃 반영
          ⇒ 예) 프레스 : 작업자 감지센서(안전BAR), 양수 조작버튼, 플라이휠 커버 등
                    도금 : 마스크 착용, 위험물(약품) 별도 보관장 마련 및 취급기준 수립
                    용접 : 안전장갑 및 보호 안경 착용, 용접 스페터 비산 방지용 보호막 설치 등
    - 작업 현장내 안전표지/수칙 게시 및 작업자 교육
    - 작업 현장내 위험요소(위험물)에 대한 사고예방 장비/시설물 설치 및 식별 표준류 반영
      1) 표준류 게시된 현위치 기준 소화 방재시설 위치 및 비상대피 동선 표기된 표준류 작성/게시
      2) 설비 간섭 등 고려 소화 방재시설 식별표, 비상대비 표시등 2층높이 반영
    - 운영중인 설비에 대한 정기 안전관리 프로세스 수립 및 이행상태
    - 설비 점검시(계획/비계획) 업무 처리절차 수립 : 2인 1개조 운영, 비정상 가동 예방절차 등', 30);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_2', 6, '설계변경, 4M 변경처리 업무절차 수립 및 준수여부', 20, '- 설계변경/4M 변경 업무 프로세스 수립여부
        [세부 유형별 업무 처리절차 및 관리분담, 고객사 ISIR 재승인 필요여부 등]
    - 변경점 추적성 확보를 위한 마스터리스트 작성관리[누락 발생시 감점 처리]
    - 변경점 누락 발생 예방을 위한 정기적인 점검활동 실시여부[담당자 지정 및 점검주기 설정관리]
    - 4M 변경품 이상여부 확인을 위한 초기유동관리 여부
    - 4M 변경이력 고객사 승인여부 확인[고객사 승인본 접수관리]', 31);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_3', 6, '품목별 도면기준 검사협정 체결 및 관리기준 준수상태 (도면 일치성)', 20, '▷ 도면에 명시된 외관, 치수, 기능, 주기를 검사협정 및 사내 검사기준 반영
    - 검사협정서/기준서/초도품 보증서 고객 승인본 보유
    - 도면 일치성 점검 담당자 지정하여 정기적 도면대비 검사협정/기준서 일치성 점검 및 점검이력 관리
    ※ 금형 노후화에 따른 성형부 마모로 중요치수 불만족 문제점 사전 검토 (치수 정기검사 항목 外 금형 마모 예상부 검사항목 추가)
   ▷ 검사협정 및 검사기준서내 부품 검사항목(정기신뢰성 시험 포함)의 점검주기 준수여부', 32);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_4', 6, '품질경영체제 구축/유지를 위한 조직구성 및 운영상태', 10, '- 품질 매뉴얼/절차서/지침서 구비 및 적용상태
    - 구체적인 업무분장 수립상태
    - SQ 인증업종 자체 내부심사[평가서 기준] 활동 실시 및 발췌 문제점에 대한 개선활동 추진
          ⇒ 점검결과 경영자/임원 보고 및 후속조치 활동 이력[증빙물 관리]', 33);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_5', 6, '자격인증 관리기준 수립 및 준수상태', 20, '- 공정별 작업자/검사자 배치기준 수립 및 자격인증 평가 실시여부 [품질 표준류내 검사지정 항목별 담당자]
          ⇒ 자격인증 실시 기준 [부적합 판별 실기평가, 품질특성 교육, 동일업무 경력, 생산품 품질산포 발생 가능성 검증 등]
      ※ 부적합 판별 실기평가
          → 외관검사 : 부적합 유형별 검출능력 실기평가
             치수검사 : 담당별 지정 계측기 사용능력 평가 [계측기 활용능력 평가로 CpK 산출 불필요]
    - 자격인증 검증평가 결과에 대한 신뢰도 확보 필요(수기 작성 원본데이터, 검증용 시료 확보 등)
    - 자격인증자 결원/휴가시 대응인원 확보상태 및 후속조치 관리방안/실행상태
    - 작업자 결원으로 대체인원 투입 불가피시, 투입전 교육/품질보증 방안 등 관리 규정 수립 및 관리 상태점검
    - 생산작업자 자격인증 : 동일작업 반복 생산후 부품간 산포발생 가능성 검증
    - 중요/특별 공정에 대한 품질검사원 확보 및 자격인증 실시 필요
          ⇒ 열처리/단조 : 조직 판독능력, 전자/조립 : 리워크 검사원, 도금/도장 : 액분석 검사원, 전자(납땜) : AOI 검사 담당자 등
      ※ 중요/특별특성 공정 자격인증평가 미실시, 허위작성 확인시 이행도 ''0''점 처리', 34);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_6', 6, '수입검사/생산공정/최종검사 부적합(추정)품에 대한 격리/식별절차 수립 및 준수여부', 20, '- 부적합품 후공정 유출 방지를 위한 식별 및 격리방안 세부 작성 및 준수여부
    - 부적합(추정)품 처리 프로세스 수립 및 준수여부
    - 공정내 부적합품 보관용 보관박스 별도 비치(RED BOX)
    - 생산중 부적합품 발생수량과 실제 수거량 비교를 통한 부적합품 후공정 유출 발생여부 점검활동 실시[점검이력 보관]
    - 개발등 시제품 생산시 양산부품과 혼입 방지를 위한 식별 및 격리 절차 수립/준수상태 점검
    - 낙하품은 처리기준 수립 및 처리이력 관리 필요 (낙하품 수량 및 처리결과 기록)
       예) 낙하품은 별도 격리/식별조치를 통한 혼입방지 및 폐기 또는 재사용(REWORK) 결정
    ※ 완성품 외관/기능 검사시 부적합 추정품 선별된 부품은 별도의 식별 표기후 동일 검사장비 또는 품질 전문검사원을 통한 재검사 진행하되,
        2차 검사 NG로 판별시 폐기처리하고 재검사 및 폐기 이력관리 (생산LOT, 재검사 사유, 재검사 결과, 폐기 수량 등)
        예) 자동 검사장비를 통한 외관(Vision)/기능 검사 1차 NG → 동일장비 2차 재검사 → 재검사 NG시 폐기
             생산라인 검사원 외관/기능 검사 1차 NG → 품질담당 전문 검사원 2차 재검사 → 재검사 NG시 폐기
              단, Rework 가능 항목으로 고객사와 협의된 부적합 항목은 Rework 진행이 가능하나, Rework 진행후 필히 라인내 검사장비 또는
              품질담당 전문 검사원의 재검사 진행 필요', 35);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_7', 6, '품질실적 점검 프로세스 수립 및 개선활동 실시상태', 20, '- 전년도 품질 실적대비 목표설정 및 실적 점검(1회/월)상태
          ⇒ 공정불량 (생산수량, 불량수, PPM), 고객불량 (납품수량, 불량수, PPM), 외주불량(입고수량, 불량수, PPM)
       ⇒ 전체, 공정별, 품목별, 불량 유형별 및 장비별(필요시) 집계
         ⇒ 공정불량률 집계 시, 재작업 수량 포함
    - 목표 미달시 워스트 항목에 대한 근본적인 원인분석 및 개선대책 수립/유효성 평가 실시상태
    - 고객 불량(필드 클레임) 문제점에 대한 고품분석 및 시정조치 활동 실시여부', 36);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_8', 6, '검사 유효성 확보를 위한 조도관리 프로세스 수립 및 준수실태', 10, '- 정기적인 작업장/ 검사장 조도 관리를 위한 운영 프로세스 수립[측정장소/시간, 조도 관리기준, 측정장소 지정]
    - 표준류내 자주/순회검사 실시구간 조도관리 포인트 누락여부
     ※ 야간작업 등 고려 일몰후 조도측정 실시, 측정산포 최소화 목적 검사위치 지정 및 손 미거치 조건
        조도측정 실시 등', 37);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_9', 6, '3정 5행 관리 프로세스 수립 및 준수실태', 10, '- 정기적인 3정5행 현장개선 프로세스 수립
     (점검 체크시트 작성, 점검 주기, 업무 분담, 지적사항 개선 시정조치 완료여부]
    - 현장점검시 3정 5행 관리실태', 38);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_10', 6, '불량부품 REWORK시 관리기준 수립 및 이행 상태', 10, '- 리워크 가능부품 선정기준 수립 및 관리상태
    - 리워크 금지부품은 폐기 처분 및 이력관리
    - 리워크품 사양확인 LOT 추적성 및 선입선출 관리상태
    - 불량부품 REWORK시 품질검사항목 설정 및 REWORK 전후 검사 이력 유지 관리상태
    - REWORK 전/후 부품의 식별 관리기준 및 준수상태
    - REWORK 제품의 출하 절차 준수 상태
    - REWORK  작업을 위한 별도 공간 운영시 작업을 위한 TOOL 및 자재의 비치 상태', 39);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_11', 6, '공정 누락 방지를 위한 작업환경 설정 상태', 10, '- 제품 생산시 공정 누락 방지를 위한 작업환경 구축 상태(공정이동 전표 활용 등)
    - 제품 생산시 자재 소진에 의한 부품 및 부자재등 누락 방지 방안 운영 상태
        → 정기적인 부자재 입고/소진량과 완제품 생산실적 비교검증 활동 실시 등', 40);
INSERT INTO sq_items (code, category_id, title, points, requirement, sort_order) VALUES ('6_12', 6, '『정성품질』 운영 프로세스는 마련되어 있고, 점검 및 포상활동은 실시되는가?', 20, '▷『정성품질』 활동 관련 업무분장(키맨)
     - 『정성품질』 수평전개 교육 담당/ 품질문제 발생시 개선활동 담당/ 고객사 협업 담당 등
  ▷ 정성품질 통신문 품질현황판 게시 및 사내 임직원 전파교육 실시 이력 관리
  ▷제조현장 『정성품질』관련 예방/개선 프로세스 수립(제조현장 반영내역 확인)
     - 예방활동 : 휴먼에러 발생 예방을 위한 작업자/공정/설비 등 예방점검 개선 이력
     - 개선활동 : 중요 품질문제(작업자 휴먼에러) 발생시 해당 공정 시정조치 활동 이력
                      → 발생 원인에 대한 세부적인 원인 분류 및 근본적인 시정조치 활동 실시
  ▷『정성품질』 유지 및 관리실태 점검 활동 실시이력(현황 및 개선대책 경영진 보고)
     - 제조현장 표준류 준수, 작업공수 일치성, 공정검사 기준 준수 등 『정성품질』 관리실태 정기적 점검이력
      ex) 제조현장 확인시 수작업 조립 어려움, 작업 공수 불명확, 역조립/오조립 가능성, 신규/임시 작업자 표준 준수 등
            『정성품질』 개선 필요항목 확인
  ▷『정성품질』 정착화 및 붐업 조성을 위한 포상제도 운영관리
     - 『정성품질』관련 사전 예방활동 및 개선 우수사례에 대한 포상제도 운영기준 수립 및 실적', 41);

-- ───── SEED: 46 reg_code↔item (qms_sqmap) ─────
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('A-4100', '1_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('A-4101', '1_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('A-5100', '6_4');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('A-5200', '6_4');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('A-8100', '6_4');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('B-1100', '6_6');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('B-2100', '6_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('B-2100', '2_9');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('B-2200', '6_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('D-1100', '6_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('F-1100', '6_5');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('F-1101', '6_5');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('F-2100', '6_5');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('H-3200', '6_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-1100', '6_2');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-1101', '1_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-1102', '1_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-1102', '6_3');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-1103', '1_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-2100', '6_2');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-3100', '6_2');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('J-4100', '6_3');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('K-1200', '2_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('K-2100', '5_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('K-2100', '5_2');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('K-2100', '5_3');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-1100', '3_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-1100', '3_2');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-1200', '3_3');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-1200', '3_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-2100', '2_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-2100', '2_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-2100', '2_8');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-2200', '2_4');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-2300', '2_3');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-3100', '2_5');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-3101', '2_6');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-4100', '6_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-4101', '6_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('L-4102', '6_7');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('M-1100', '1_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('M-1200', '1_2');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('M-2100', '5_1');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('M-2100', '5_3');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('M-3100', '2_8');
INSERT INTO sq_reg_map (reg_code, item_code) VALUES ('M-4100', '6_9');

-- ───── SEED: 46 지배규정 ─────
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('1_1', 'A-4100', '문서 및 자료 관리 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('1_1', 'A-4101', '관리표준작성 지침', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('1_1', 'J-1101', '공정FMEA 작성 및 관리 지침', '개발팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('1_1', 'J-1102', '관리계획서 작성 및 관리 지침', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('1_1', 'J-1103', '작업표준서 작성 및 관리 지침', '생산팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('1_1', 'M-1100', '생산관리 규정', '생산팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('1_2', 'M-1200', '공정관리 규정', '생산팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_1', 'K-1200', '협력업체 관리 규정', '구매팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_1', 'L-2100', '검사업무 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_3', 'L-2300', '한도견본관리 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_4', 'L-2200', '신뢰성 시험업무 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_5', 'L-3100', '계측기관리 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_6', 'L-3101', '측정시스템 평가 지침', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_7', 'L-2100', '검사업무 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_8', 'L-2100', '검사업무 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_8', 'M-3100', '완성품 관리 규정', '영업팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('2_9', 'B-2100', '시정조치 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('3_1', 'L-1100', '설비관리 규정', '생산기술팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('3_2', 'L-1100', '설비관리 규정', '생산기술팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('3_3', 'L-1200', '지그관리 규정', '생산기술팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('3_7', 'L-1200', '지그관리 규정', '생산기술팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('5_1', 'K-2100', '자재관리 규정', '구매팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('5_1', 'M-2100', '식별 및 추적성관리 규정', '생산팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('5_2', 'K-2100', '자재관리 규정', '구매팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('5_3', 'K-2100', '자재관리 규정', '구매팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('5_3', 'M-2100', '식별 및 추적성관리 규정', '생산팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_1', 'D-1100', '제품안전관리 규정', '개발팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_2', 'J-1100', '개발업무 규정', '개발팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_2', 'J-2100', '양산부품승인업무규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_2', 'J-3100', '4M변경관리 규정', '개발팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_3', 'J-1102', '관리계획서 작성 및 관리 지침', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_3', 'J-4100', '도면관리 규정', '개발팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_4', 'A-5100', '내부심사 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_4', 'A-5200', '공정 및 제품심사 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_4', 'A-8100', '리스크 관리 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_5', 'F-1100', '교육훈련 규정', '총무팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_5', 'F-1101', '신규보직자 관리 지침', '총무팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_5', 'F-2100', '사내 자격관리 규정', '총무팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_6', 'B-1100', '부적합품 관리 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_7', 'B-2100', '시정조치 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_7', 'B-2200', '지속적 개선업무 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_7', 'H-3200', '고객 불만처리 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_7', 'L-4100', '통계적 기법적용 규정', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_7', 'L-4101', '관리도 운영 지침', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_7', 'L-4102', '공정능력 운영 지침', '품질보증팀');
INSERT INTO sq_item_docs (item_code, doc_code, doc_name, dept) VALUES ('6_9', 'M-4100', '3정5S활동 규정', '생산팀');

-- ───── SEED: 58 기대 양식유형 ─────
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_1', '관리계획서(Control Plan)', 187);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_1', '작업표준서', 215);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_1', '공정FMEA', 57);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_1', '공정흐름도(공정도)', 189);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_1', '설비일상점검표', 73);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_2', '설비 정기점검', 114);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_3', '작업표준서', 215);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_4', '자주/순회검사 체크시트', 399);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_5', '브레이징로 점검', 189);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('1_5', '작업표준서', 215);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_1', '검사협정서', 251);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_1', '수입검사 기준서', 100);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_1', '수입검사 일지/이력', 208);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_2', '수입검사 관리대장', 6);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_2', '수입검사 일지/이력', 208);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_3', '한도견본', 48);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_4', '정기검사(신뢰성)', 405);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_4', '시험성적서', 1843);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_4', '인장시험 성적서', 37);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_4', '도금두께 측정', 236);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_5', '계측기/검교정', 170);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_6', '게이지 R&R', 76);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_7', '자주/순회검사 체크시트', 399);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_8', '완성품/출하 검사', 315);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('2_9', '리크/리워크', 749);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('3_1', '설비일상점검표', 73);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('3_2', '설비 정기점검', 114);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('3_3', '지그/치공구', 663);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('3_4', '설비일상점검표', 73);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('3_5', '브레이징로 점검', 189);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('3_6', '설비일상점검표', 73);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('3_7', '지그/치공구', 663);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('4_1', '금형관리', 666);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('4_2', '금형관리', 666);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('4_3', '금형관리', 666);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('4_4', '금형관리', 666);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('4_5', '금형관리', 666);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('5_1', 'LOT 추적성/선입선출', 64);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('5_2', '자재 보관관리', 58);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('5_3', '식별관리', 116);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('5_4', '용기/적재 표준화', 90);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_1', '안전관리', 112);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_2', '4M/설계변경', 601);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_2', 'ISIR/PPAP 승인자료', 493);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_2', '공정FMEA', 57);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_3', '검사협정서', 251);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_3', '도면', 416);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_3', '관리계획서(Control Plan)', 187);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_4', '품질매뉴얼/절차서', 224);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_5', '자격인증/교육', 842);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_6', '부적합/특채', 368);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_6', '식별관리', 116);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_7', '품질실적/개선', 1696);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_8', '조도관리', 21);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_9', '3정5행/5S', 63);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_10', '리크/리워크', 749);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_11', '작업표준서', 215);
INSERT INTO sq_item_form_types (item_code, form_type, count_in_archive) VALUES ('6_12', '품질실적/개선', 1696);
